### ISSUE TITLE
Restore from Live to Development is failing with error: PublicAccess member group DistributorsGroupName could not be found

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco.Cloud.Issues#1]
<p>In the Development environment - go to Content, do right mouse click, chose Restore, specify &quot;Restore your website from Live&quot; and click &quot;Restore from Live&quot; button. After a short time an error will occur:
&quot;The source environment has thrown a Umbraco.Deploy.Exceptions.RemoteApiException with message: The remote API has thrown an exception. It might have been caused by an inner Umbraco.Deploy.Exceptions.EnvironmentException with message: PublicAccess member group DistributorsGroupName could not be found.&quot;</p>
<p>The member group DistributorsGroupName was deleted from the repository and there is no references to it in the project.
After a long thread with Umbraco Support, they have confirmed that it is a bug in Umbraco Core. Please, see the attached document - &quot;CommunicationThreadWithUmbracoSupport.docx&quot;.</p>
<p>Further investigation has shown that this error occurs only when public access is set up for the RMA &amp; Claims node. When restoring content from Development to Local environment, it works fine and without errors, since the public access is not set up in Development (see screen shots attached).</p>
<p>Issue imported from old issue tracker: <a href="https://issues.umbraco.org/issue/U4-10621">U4-10621</a><p><strong>Note: This issue has attachments in the original issue</strong></p>

**Comment by pijemcolu** [comment]
Thanks for the issue report.

Just to confirm and re-iterate the problem here, in order to reproduce the issue:
0. On a two environment project ...
1. Create a member group
2. Create a content node
3. Set-up public access for the content node, only allowing the member group created in step 1
4. Sync-up the environments.
5. Delete the member group from one of the environments.
6. Restore content to the environment where the member group is deleted - This will result in a content restore issue.
