### ISSUE TITLE
TLS compliance according to danish law

### ISSUE THREAD

**Issue by Cjschmidt** [umbraco/Umbraco.Cloud.Issues#137]
Article: https://sikkerdigital.dk/myndighed/tekniske-tiltag/tekniske-minimumskrav/

This law states some technical requirement sthat is currently not available on the Cloud platform. These requirements must be implemented before 1. January 2020
One of these are the support of TLS 1.0 and TLS 1.1 needs the be removed. 
The Cloud platform still supports these protocols :

(eucl.dk)

![image](https://user-images.githubusercontent.com/12168304/67553916-93a24980-f70e-11e9-8e69-f9ae79001568.png)

---
_This item has been added to our backlog [AB#5256](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5256)_

**Comment by nul800sebastiaan** [comment]
Thanks, we're still determining what the impact will be for all people visiting sites on Cloud. 

The TLS version is a setting that is only available for the whole server so we can't disable it per site, it needs to be changed for the entire platform.

While we don't offer ONLY TLS 1.2 quite yet, it is possible to use Cloudflare in front of your Cloud website so you can tweak the TLS and other settings yourself.

**Comment by Cjschmidt** [comment]
@nul800sebastiaan  
Alright.

Cloudflare is currrently the solution I'm discussing with my customer, but I thought it would be a good idea for Umbraco Cloud to be able to comply with this law. It would also be a nice security update for the platform to get rid of at least the 1.0 protocol, as it is vulnerable to man-in-the-middle attacks

**Comment by nul800sebastiaan** [comment]
I just realized (and my Danish is not great): does the new law specify that the server is no longer allowed to offer TLS 1.0/1.1? As far as I read it, this says that the server needs to offer 1.2, which we do.

**Comment by nul800sebastiaan** [comment]
> the 1.0 protocol, as it is vulnerable to man-in-the-middle attacks

As far as I know this is a theoretical vulnerability where if you really really really want to break the encryption you can do it with a very powerful computer, and then only 1 request at a time, so it's going to take an amount of effort that is not actually feasible. Correct me if I'm wrong.

Please note that if this ever changes, SSL Labs will immediately downgrade everybody's grade from an A to something lower.

**Comment by Cjschmidt** [comment]
@nul800sebastiaan SSL Labs will do this from january 2020:

![image](https://user-images.githubusercontent.com/12168304/67558655-ad945a00-f717-11e9-86d5-95a1529639b7.png)

The requirement says 'Minimum 1.2' - which means you're not allowed to be able to use 1.1 and 1.0
I have just contacted Digitaliseringsstyrelsen to ask for some elaboration on the requirement - I'll return here with the reply when I get it

**Comment by nul800sebastiaan** [comment]
Awesome! I had not checked for a while, good to know, thanks!

**Comment by dawoe** [comment]
Hi @nul800sebastiaan 

Any news on this one ?

Dave

**Comment by sitereactor** [comment]
This is currently work in progress. I don't have a date for when its done, but we are currently testing this internally.

**Comment by jevgenigeurtsencolours** [comment]
Hi @sitereactor,

Any updates about this ticket? 

Thanks in advance!

**Comment by pijemcolu** [comment]
Hi @jevgenigeurtsencolours. We'll be announcing a plan any day now where we'll only allow TLS1.2 as accepted protocol for websites.

We expect to be rolling out updates which would enforce this in March.

**Comment by c9mbundy** [comment]
I believe that all major browsers are about to cease support of TLS 1.0 and 1.1

Google is due to cease support on March 31 with Chrome-81 and all other major browsers have similar schedules.  https://security.googleblog.com/2018/10/modernizing-transport-security.html

The current recommendation from all major browsers is migrate to TLS 1.3 by that date.

**Comment by sitereactor** [comment]
Yes, that's correct. I expect that we will announce TLS 1.0 and 1.1 being discontinued on Umbraco Cloud next week. We usually give 14 days notice on a service window and then there will be one week in which sites are updated before TLS 1.0 and 1.1 are removed.
Given this notice everyone should have 3 weeks to make necessary changes.

The details will be sent out to all technical contacts and added to our statuspage.

**Comment by c9mbundy** [comment]
Might that also enable the use of http/2 (which requires minimum of TLS 1.2) or is that a step too far for Umbraco-Cloud?

**Comment by sitereactor** [comment]
Our current infrastructure doesn't support http/2 unfortunately, but good news is that we are starting a larger Project to modernize the Platform, so it will happen. We'll share more details once we are closer to something more concrete.

**Comment by johannusNL** [comment]
TLS compliance 'according to danish law', I would say: Security by design and adopt best practice as been used all over the world. This is a major issue for all websites hosted by Umbraco Cloud.
I can't imagine why it took so long before Umbraco addressed this. The action to correct this is way to late.

**Comment by johannusNL** [comment]
> Hi @jevgenigeurtsencolours. We'll be announcing a plan any day now where we'll only allow TLS1.2 as accepted protocol for websites.
> 
> We expect to be rolling out updates which would enforce this in March.

Any update on the announcement?

**Comment by nul800sebastiaan** [comment]
Yes, we're also unhappy with the timing of this, but this is how it is right now. We're working on it and this issue will be updated when the announcement is ready.

As a sidenote, and not to be defensive: there is currently nothing inherently "wrong" with TLS 1.0/1.1. They are not wide-open security holes that can be abused (https://docs.microsoft.com/en-us/security/solving-tls1-problem#the-current-state-of-microsofts-tls-10-implementation). However, compute power is getting cheaper and cheaper year over year, which will eventually make it cheap enough to brute force TLS 1.0 message that get intercepted. This is why browsers are currently deprecating protocols, and we're of course working on that as well, albeit much later then we wanted to.

**Comment by c9mbundy** [comment]
@nul800sebastiaan - not wanting to be critical, as I appreciate the issues involved, but all of the major browsers announced that they would remove support of TLS-1.0/1.1 on March-31 back in 2018, and I believe that Microsoft has supported TLS-1.2 since .Net-4.5.2.  However, Umbraco-Cloud is certainly no Robinson Crusoe when it comes to leaving this to the last minute. I also work with WPEngine and their Cloud hosting platform for WordPerfect sites, and they are also only rolling out their migration to TLS-1.3 and discontinuance of TLS-1.0/1.1 beginning from March-1

**Comment by nul800sebastiaan** [comment]
Yes, we're also unhappy with the timing of this on our side. :-)

**Comment by johannusNL** [comment]
Not only to comply to Danish Law and other foreign law, but also to comply to PCI DSS standards. The FAQ on the Umbraco-Cloud mentions that Azure is PCI compliant, thus Umbraco cloud does it too..
But, since [PCI DSS explicitly forbids the use of TLS1.0.](https://www.pcisecuritystandards.org/documents/Migrating-from-SSL-Early-TLS-Info-Supp-v1_1.pdf) This configuration parameter is not Azure dependent but dependent on the configuration of the Umbraco Cloud environment.

I think, the Umbraco statement about PCI is not correct. All Cloud users with PCI requirements are not compliant at the moment.

Don't get me wrong, I don't want to be a a pain in the ass, but just being critical on this subject.

**Comment by johannusNL** [comment]
OWASP, what's called the best practice/web development bible, states that when using TLS 1.0, from compatibility perspective, should have Downgrade attack prevention
["Where legacy protocols are required, the “TLS_FALLBACK_SCSV” extension should be enabled in order to prevent downgrade attacks against clients."] [https://owasp.org/www-project-cheat-sheets/cheatsheets/Transport_Layer_Protection_Cheat_Sheet](url)

Umbraco-Cloud configurations doesn't have this configured according to SSLLabs:
Downgrade attack prevention | No, TLS_FALLBACK_SCSV not supported.

I would recommend to follow such best practices and requirements from the numbers of standards available to secure websites/applications

**Comment by johannusNL** [comment]
Free advice, please pay attention. Do not only terminate the use of TLS 1.0 and 1.1. But make sure the ciphers are configured strong.
The Dutch National Center Cybercrime has a nice document which helps you choosing the right ciphers [https://www.ncsc.nl/binaries/ncsc/documenten/publicaties/2019/mei/01/ict-beveiligingsrichtlijnen-voor-transport-layer-security-tls/ICT-beveiligingsrichtlijnen-voor-Transport-Layer-Security-v2.pdf](url)

Good:
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

sufficient:
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
TLS_DHE_RSA_WITH_AES_256_CBC_SHA
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
TLS_DHE_RSA_WITH_AES_128_CBC_SHA

Stop using:
TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA
TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA
TLS_RSA_WITH_AES_256_GCM_SHA384
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_256_CBC_SHA256
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_AES_128_CBC_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_3DES_EDE_CBC_SHA


So does ssllabs too [https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices](url)

**Comment by nul800sebastiaan** [comment]
Okay, we do really get it @johannusNL - we are working on it.

We're also working on ciphers but that's a next step.

**Comment by pijemcolu** [comment]
In the process of updating docs: https://github.com/umbraco/UmbracoDocs/pull/2319

**Comment by johannusNL** [comment]
> Okay, we do really get it @johannusNL - we are working on it.
> 
> We're also working on ciphers but that's a next step.

I wasn't aware, when looking at the sprints, that the ciphers where addressed too. These subjects are strongly related to each other. From previous reactions and the slow response on this issue rise a feeling that the awareness on this subject is not on top of mind. 
So I wouldn't say 'we do really get it'. Some gratitude to a concerning community, willing to help you, would be fair.

**Comment by nul800sebastiaan** [comment]
I do apologize for the frustrated reply @johannusNL - I just couldn't figure out how to keep saying the same thing that we're actively working on it! 😅

Thanks very much for trying to keep us sharp all! 💓

**Comment by sitereactor** [comment]
The final parts of the maintenance related to discontinuing TLS 1.0 and 1.1 has been done, so closing this issue as Umbraco Cloud now supports a minimum of TLS 1.2.

* TLS is in compliance with danish law.
* SSLLabs rating is now back to an A-rating.
* Its not an A+ because SSLLabs classifies some ciphers as weak, but some of these we cannot remove due to infrastructure constraints.

**Comment by pijemcolu** [comment]
Hello everyone. 

Since yesterday we now support only TLS1.2 for Umbraco Cloud Websites. We also only support Strong or sufficient ciphers according to SSL labs docs: https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices#23-use-secure-cipher-suites .
