### ISSUE TITLE
Don't run deployment commands, when pushing other branches than master

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco.Cloud.Issues#14]
Working the cloud developer course I ran into this one again.

Copied from https://issues.umbraco.org/issue/UAAS-648

> When pushing content in other branches than master, all the deployments commands are run.
> 
> Is this necessary? 
> As I understand, only changes to the masterbranch gets deployed. 
> So this just adds some annoying waiting time, when pushing updates.

**Comment by sitereactor** [comment]
We will soon accommodate this.
We are currently working on some features related to Deploy where we will implement this.

**Comment by skttl** [comment]
Sounds great, looking forward to this 👍

**Comment by sitereactor** [comment]
So this issue suddenly got a bit old ... What I expected to happen back in October didn't go in the direction we expected at the time, so the bits didn't get implemented along with Deploy.

I do however have a solution for this, which I can apply to any repository on Cloud. Just reach out if you want to try it out.

**Comment by nul800sebastiaan** [comment]
Hi @skttl , going through some old issue reports. We are in the process of moving to an improved Cloud platform and that is going to be our main focus for the foreseeable future. 

This feature request is really good and when we're done moving to the new platform we will need to work on making a good workflow for branching. There's a related issue to this as well, https://github.com/umbraco/Umbraco.Cloud.Issues/issues/37 which is an existing problem with branching as well. We'll group these types of issues together.

**Comment by sajumb** [comment]
Hi @skttl,
I don't have a specific update on this one. However, we will soon start working on performance improvement in the deployment flow. Both within the Umbraco Deploy product as well as in deployment section of the platform itself. In this work, we will consider the possible to avoid running all commands when working on a feature branch.

Thanks for highlighting this.

**Comment by skttl** [comment]
I fiddled with the post-receive hook in kudu, if you change it to this:

```
#!/bin/sh

# Read input data from git
while read oldrev newrev refname
do
    # Check if the branch being pushed is master
    if [ "refs/heads/master" = "$refname" ]; then
        # Record the push information to a file
        echo "$oldrev $newrev $refname" > pushinfo

        # Execute the deployment script only if it is the master branch
        "$KUDU_EXE" "$KUDU_APPPATH" "$KUDU_MSBUILD" "$KUDU_DEPLOYER"
    fi
done
```

it will only run the deployment command when pushing to master

**Comment by mclausen** [comment]
Hi @skttl,

It looks like this issue has been around for quite a while, and there have been promises of it being reviewed and prioritized.

From the Platform perspective, it doesn’t make much sense for us to support multiple branching strategies in the Cloud repositories, because these repositories are mainly meant for deployments. This discussion falls into a bit of a gray area since git supports it, but the repositories are intended for deployments. We’re concerned we might run into limitations and unforeseen consequences if we try to work around how the deployment git repositories function.

For Umbraco Cloud, we recommend cloning the deployment repositories within your own git provider and [integrating CI/CD](https://docs.umbraco.com/umbraco-cloud/set-up/project-settings/umbraco-cicd) into your workflows. This way, you can enjoy all the advanced branching strategies and development flows your heart desires!

Kind regards,
@mclausen - Cloud Platform Team Lead

**Comment by mikkelhm** [comment]
Hy everyone - im closing this one down we actually implemented the feature last week as part of another workflow. 

What happens now is that upon commit, we do check if the commit was done to the master branch, if not, the we abort. 

As cloud only supports one branch, we still dont recommend using other branches, as they are not preserved when doing certain operations, as well as they will never be deployed anywhere. 

The CI/CD flow feature, is the best option to be able to work with branches on your local code/git repositories, which then in turn will be merged into the mater branch of the cloud repositories upon deployments.
