### ISSUE TITLE
Sending mail from Umbraco Cloud

### ISSUE THREAD

**Issue by martindotcontrol** [umbraco/Umbraco.Cloud.Issues#162]
As mentioned on https://our.umbraco.com/documentation/Umbraco-Cloud/set-up/SMTP-settings/ an SMTP server is not part of the cloud solution. However sending mail from your website does feel like a bare necessity. We have good experiences with SendGrid and on Azure you can freely send 25K mails per month.

Could this (or something similar) ever be incorporated as a service in Umbraco cloud ?

**Comment by nul800sebastiaan** [comment]
We have looked into partnering with Sendgrid and others but unfortunately the cost for this was prohibitive to be able to provide this functionality. Free options are only available if you're not running a platform as service. 😅

We will keep investigating this as an add-on feature in the future. Therefore, I am closing this issue and adding the `idea` label. We regularly review feature requests on the `idea` list, to get extra inspiration for what to work on next. So it doesn't mean this issue is closed forever, but it is not being worked on for now. 

Thanks for the great feature request! 👍
