### ISSUE TITLE
UC-7.15.4 - Fail to restore from Live - System.IO.PathTooLongException on Media

### ISSUE THREAD

**Issue by c9mbundy** [umbraco/Umbraco.Cloud.Issues#195]
An Umbraco-Cloud 7.15.4 site that is functioning as normal, but can't restore to local development site.

Fails to restore due to an inner exception caused by media supposedly having file and/or directory names greater than 260/248 chrs respectively.

However, the live site is functional, and the example given in the deploy exception would not seem to indicate it is actually violating the conditions described by the exception.

Even the  fully qualified url length in the example given by the exception is only 128chrs.

I suspect the deploy is actually throwing the exception based on file-name > 80chrs which is clearly way too short, and not actually violating the limits for Media storage.

Example:
-- EXCEPTION ---------------------------------------------------
 (proper exception traces at the end of this log)
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
System.AggregateException: One or more errors occurred.
Umbraco.Deploy.Exceptions.ProcessArtifactException: Process pass #0 failed for artifact umb://media-file/1450/if-you-obey-all-the-rules-you-will-miss-all-the-fun-katharine-hepburn-768x384.jpg.
----------------------------------------------------------------

**Comment by nul800sebastiaan** [comment]
Hi @c9mbundy 

> I suspect the deploy is actually throwing the exception based on file-name 

No we're just catching the orignally exception and re-throwing it. Due to the setup of the file system you will get this error with quite "short" looking filenames anyway, since the complete path is too long. Unfortunately this is not something we can fix since we can't fix Windows 🙈 

There's a few other factors at play where the path would turn to be too long, I can't remember what exactly.
We've documented how to fix this problem right here: https://our.umbraco.com/documentation/Umbraco-Cloud/Troubleshooting/Deployments/Path-too-long-exception/#path-too-long-exception

Additionally, you could investigate switching to using Azure Blob Storage for your Cloud sites, blob storage allows for file names of any length (well.. int.Max I guess) to be stored.

Work is on the way to upgrade our infrastructure which would eliminate this problem but there's no date for that yet, I don't expect that to be ready any time soon.
