### ISSUE TITLE
Respecting package.config

### ISSUE THREAD

**Issue by Chuhukon** [umbraco/Umbraco.Cloud.Issues#198]
It will be a big plus if the git repo on Umbraco cloud has a package.config or at least respect it by updating version numbering of the packages done by the cloud services. When a package.config is available a multiple simple team workflows can be integrated more easily by still respecting that we have to play a round with a "core" and "web repository". Multiple blog posts are currently challenging this situation;

- https://skrift.io/articles/archive/take-two-another-approach-for-team-development-workflow-with-umbraco-cloud/
- https://skrift.io/articles/archive/integrating-umbraco-cloud-with-team-development-workflow/
- https://shazwazza.com/post/web-application-projects-with-umbraco-cloud/

A package.config can be establish is the following;

- Pull latest from cloud
- Run a nuget consolidate on your solution which will result in version differences between the "integration" projects and the umbraco cloud website project.
- The consolidation will be executed after which all projects in the solution are on the same version.

With this in mind you you assure;

- The project is using the power of Umbraco cloud automatic updates
- Teams can create a workflow (as easy of complex they want)  where they keep all custom code in there core project (and repo)

As discussed with the cloud support team via intercom this is currently not possible.

**Comment by nul800sebastiaan** [comment]
We create a package.config for you when you follow the following instructions: https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/

We're definitely aware of the flaws of that setup and wish to improve that in the future, this is on a long term list of wishes. The first step for that is currently in progress and that is to change the underlying platform of Cloud so that we can actually implement the rest of the improved developer workflow. This is going to take a while though, so a bit of patience is required. 

As said: there's no immediate great solution but the link above gets you a pretty long way. I'll close this for now with the message: yep, we want to improve this and we're working on it! Thanks for the report!
