### ISSUE TITLE
Languages not removed properly between deployments

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco.Cloud.Issues#207]
Deleting one or more languages on an environment, and transferring that change to another environment, does not cause the language to actually be removed from the target env.

Reproduction
------------

1. Create a project on Cloud, with Dev and Live envs
2. Add another language (minimum 2 languages total) on Dev
3. Deploy that change to Live - the language will be added correctly in the backoffice
4. On Dev, delete one of the languages in the backoffice
5. Deploy that change to Live
6. Observe the latest changes on the cloud which report that a language was removed - however, in the Live backoffice the "deleted" language will still be present

**This can result in schema mismatches when restoring content.**

A relatively easy fix - deleting the language manually on target environment does the job.

I have noticed that running a manual extraction via KUDU re-generates the language UDA, which indicates it is still saved in the database and not updated with a deployment.

**Comment by nul800sebastiaan** [comment]
This is expected behavior: https://our.umbraco.com/documentation/Umbraco-Cloud/Deployment/Deploying-Deletions/#deleting-backoffice-languages

**Comment by Jay-umbr** [comment]
@nul800sebastiaan I put that section in the documentation when I discovered the issue. I do not think this is an expected behaviour - if adding a language is properly logged, deleting it should not involve any workarounds.

**Comment by nul800sebastiaan** [comment]
As a rule of thumb, I think it goes for pretty much most things Deploy. We don't want to delete stuff based on something just being non-existing in git anymore. This could simply have been a merge error and ending up removing something from git - then causing the entire thing to be deleted in umbraco.. and all history goes with it so it can't be reverted.

This is expected behavior and we have no immediate plans to change this.

**Comment by Jay-umbr** [comment]
That makes sense - thanks for clearing it up 👍
