### ISSUE TITLE
Umbraco Cloud IPv6 support

### ISSUE THREAD

**Issue by rudgr** [umbraco/Umbraco.Cloud.Issues#210]
The advisory of a 3rd party penetration test on one of our Umbraco Cloud sites was to configure a IPv6 address:

https://internet.nl/faqs/ipv6/

After discussing with Umbraco Support, it turns out that Umbraco Cloud does not support IPv6 (yet). Umbraco Support suggested to add this feature request... so here it is :)

Would be great (and secure) if this could be considered/added, tx!

related issue: #192

**Comment by sitereactor** [comment]
Hi @rudgr thanks for posting your feature request and sorry about the delay in getting back to you.
IPv6 is something we want to support, but its not currently possible on our existing infrastructure.
But we are in the process of modenizing our Cloud Platform, so we can support capabilities like IPv6 and HTTP/2 to name a few. I don't have a time frame for this specific ask, but its hopefully something you'll see pop up in Q4 of this calendar year.

I have added it as a "sprint idea" so we can track it and update this post once IPv6 is available on Umbraco Cloud.

**Comment by nul800sebastiaan** [comment]
As an option for now, in the mean time, you could consider running the site behind Cloudflare so you have the option to use IPv6 now. 

FYI: as I understand it, IPv6 is not inherently more secure, it all depends on proper configuration (https://blog.apnic.net/2019/03/18/common-misconceptions-about-ipv6-security/). I would assume that Cloudflare does provide those benefits, but I haven't verified that.

**Comment by rudgr** [comment]
Tx for the “tip” :)

**Comment by rudgr** [comment]
Just a quick update that we received the same request form another client. I agree that it might not really be more secure, but since both clients are in the enterprise/governance space, it might be good for umbraco cloud enterprise ambitions to add this :)

**Comment by giordanop** [comment]
@nul800sebastiaan  FYI: by December 31 2021, all Dutch governments must be reachable via Internet Protocol version 6 (IPv6) https://www.forumstandaardisatie.nl/ipv6.

**Comment by sitereactor** [comment]
If you use dns.umbraco.io when configuring the DNS settings for your hostname it will be using IPv6 behind the scenes.

I'm curious though if the IPv6 requirement is specially around AAAA records over A-records or that a hostname must use an AAAA record 🤔

**Comment by nul800sebastiaan** [comment]
I didn't do anything with AAAA records, just `dns.umbraco.io`  and my site can be reached over IPv6. From what I understand from that link, that is all that is required.

![image](https://user-images.githubusercontent.com/304656/146017492-0a0e8b1e-4db5-4d8e-a7d5-75b1a6b902c4.png)


![image](https://user-images.githubusercontent.com/304656/146017915-d1278c97-e1ea-4d51-998b-6cf487172928.png)

**Comment by nul800sebastiaan** [comment]
Although I do see now that Cloudflare might have set that up automatically for me, not sure where that AAAA record comes from.

**Comment by ronaldbarendse** [comment]
@nul800sebastiaan You're using Cloudflare's CNAME flattening on your root domain, so all the A and AAAA records are fetched from dns.umbraco.io and then returned (as if you'd configured them manually). If you can't use this feature, our current documentation states to only add a single A record: https://our.umbraco.com/documentation/umbraco-cloud/Set-up/Manage-Hostnames/#domains. This is probably why there's some confusion about IPv6 support now, as the documentation doesn't indicate it and following the instructions won't give you full support either (in case you can't use a CNAME record).

@sitereactor Are there any objections to configuring all the A (`104.19.191.28` and `104.19.208.28`) and AAAA (`2606:4700::6813:bf1c` and `2606:4700::6813:d01c`) records manually?

**Comment by sitereactor** [comment]
>Are there any objections to configuring all the A (104.19.191.28 and 104.19.208.28) and AAAA (2606:4700::6813:bf1c and 2606:4700::6813:d01c) records manually?

Sorry, I don't understand what you mean by configuring the records manually 🤔 

The AAAA records you wrote or not officially supported by Cloudflare, so they cannot be used for custom hostname enrollment.

**Comment by ronaldbarendse** [comment]
@sitereactor If you want to configure your root domain to point to Umbraco Cloud, but your DNS provider doesn't support CNAME flattening, configuring these A and AAAA records manually would result in the same records being returned, right? This is not for custom hostname enrolment, but actually accessing the site via Cloudflare's IPv6 addresses.

In that case, it doesn't matter (from a functional view) whether you're using a CNAME to `dns.umbraco.io` or have manually configured the records, as long as it returns the same:

![Resolve-DnsName dns.umbraco.io](https://user-images.githubusercontent.com/1051287/146527326-da2a0237-bf37-4c48-b4f4-8fb69a35f6ea.png)

Using the CNAME will make DNS management a lot easier: Umbraco/Cloudflare can easily add more A or AAAA records and there's probably less issues with setting that up, so I'd still strongly suggest using that if possible. But if it's not (aka you want to configure a root domain and your provider doesn't support CNAME flattening), you already need to manually configure at least one of the A records: why not document the AAAA records as well?

**Comment by sitereactor** [comment]
It's not supported by Cloudflare. I have asked about this multiple times and the response is that only the IPv4 IPs are supported when enrolling a custom hostname. You cannot use the IPv6 addresses and expect it to work. 
In theory, yes sure, but in reality, no, its not officially supported.

I know that many will want/need to use an A-record to setup the root domain, but they will have to use the IPv4 for the enrollment until the IPv6 enrollment is supported. That's why we can only say that if IPv6 is a hard requirement then you will need to use the dns.umbraco.io CNAME approach.

**Comment by pijemcolu** [comment]
Hello everyone.

IPv6 works on Umbraco Cloud. In order to test this I had to enable IPv6 locally on my machine. After enabling IPv6 as the only IP addressing protocol a website on Umbraco Cloud works using only IPv6 AAAA record.

1. Enable ipv6 support on your client (windows - couple clicks in control panel) - https://networking.grok.lsu.edu/article.aspx?articleid=17571&printable=y
2. Create a website with IPv6 only AAAA record - tomanka.com
3. Confirm ipv6 only AAAA records using `dig`
4. Confirm website loads

`dig tomanka.com AAAA` returns 
```
;; ANSWER SECTION:
tomanka.com.            300     IN      AAAA    2606:4700:7::7d
```

Visiting https://tomanka.com in your browser will show a website running on Umbraco Cloud using ipv6 only.

To test whether your client you can use google endpoints to figure out whether your host supports connecting over ipv6 or ipv4.
You can have ipv4 or ipv6 enable as the only ip addressing protocol in your network properties (https://networking.grok.lsu.edu/article.aspx?articleid=17571&printable=y)
ip4.google.com supports ipv4 only
ip6.google.com supports ipv6 only

I'll be closing this issue as the original request is about supporting IPv6 in Umbraco Cloud. I believe the CNAME flatenning part of the conversation and the confusion about CNAME vs A vs AAAA records is a DNS detail and doesn't have anything to do with IPv6 support. The documentation states that you can use AAAA records to add hostnames that support ipv6.
