### ISSUE TITLE
Some files (installation files) are not blocked when IP is not in the whitelist

### ISSUE THREAD

**Issue by crixlis** [umbraco/Umbraco.Cloud.Issues#211]
The Umbraco Cloud IP-whitelist feature does not block all URLs from uninteded (when IP is not in the whitelist) views. 

### Bug summary
Unintended access is possible to files/pages which normally should be blocked when an IP is not in the IP-whitelist.

### Specifics
This issue came up with a penetrationtest for the customer and I noticed this was not website specific, but probably a bug. I rather not put the specific URL here, but if needed i can send it through DM. I tested this on different Umbraco Cloud websites. 

### Steps to reproduce

1. Go to a Umbraco Cloud website with an IP that is not in the IP-whitelist
2. Add /umbraco/views/install/database.html behind the URL.
For instance: https://dev-projectname.s1.umbraco.io/umbraco/views/install/database.html
3. You should now be able to visit the page without logging in.

### Expected result

The specific URL is not visible (unless you have a whitelisted IP). You should always see the credential screen.

![credentialscreen](https://user-images.githubusercontent.com/16986981/82669370-a0066a80-9c3b-11ea-9d68-99a348c850bb.jpg)

### Actual result
The specific URL is directly visible. Without entering credentials.

Screenshot:
![bug_umbracoCloud](https://user-images.githubusercontent.com/16986981/82668772-7d278680-9c3a-11ea-9741-93601a6e360e.jpg)

**Comment by nul800sebastiaan** [comment]
Thanks @crixlis - we're aware that static files are not blocked since the basic auth runs as an httphandler, so anything not processed by the asp.net pipeline won't be blocked. 

Of course if you are worried about this you could try to add an IP filter. 

Other than that, we don't believe this opens up any kind of security hole. Anything that would need to be posted to a server will be rejected as the correct authentication is not available. Let us know if you can think of any way this would compromise security otherwise.

Finally, we are working on replacing the authentication mechanism in the next few months, which should completely block any file to be accessed. 

I'll close this for now, but do comment if there's anything nefarious that this can actually be used for. 👍
