### ISSUE TITLE
Heartcore: Unable to create, edit, or use content templates

### ISSUE THREAD

**Issue by jfm5248** [umbraco/Umbraco.Cloud.Issues#218]
When attempting to use the content template feature in Umbraco Heartcore using both methods outlined in the [documentation](https://our.umbraco.com/documentation/getting-started/backoffice/Content-Templates/), the template is either not created, or not in a usable state.

### Bug summary

**Method 1**

- Create items in the content tree that I would like to template.
- Right click the "Brand" node and select "Create content template"
- Name it "Brand Style" and submit.
- Receive confirmation that the template has been created.

![image](https://user-images.githubusercontent.com/10039128/83259585-54e1df80-a186-11ea-8fb8-ffd3875f233a.png)

**Expected behavior**
I should be able to edit and use the content template per the documentation.

**Actual behavior**
Content template appears under Settings, but "No content can be added for this item" and no other options appear. It does not appear as an option when attempting to create new items under the "Styles" content tree item.

![image](https://user-images.githubusercontent.com/10039128/83259487-1ea46000-a186-11ea-9c8a-4b2894be7c86.png)

**Method 2**

- Under Settings, right click on Content Templates and click "Create..."
- Select the appropriate document type

![image](https://user-images.githubusercontent.com/10039128/83259336-dd13b500-a185-11ea-93ab-361fecd3085f.png)

**Expected behavior**
The content template should be created and usable per the documentation.

**Actual behavior**
After clicking the document type to template, the dialog disappears without any confirmation. No template item is created.

**Comment by sitereactor** [comment]
Hi @jfm5248 thanks for reporting this. We will have a look at it in our upcoming sprint starting next week.

I'll report back as soon as I know, but this feature should work in Heartcore as well. My guess is that the templates rely on something, which is not available in Heartcore, so we'll figure out how to get it working again.

**Comment by sitereactor** [comment]
Hi @jfm5248 sorry about the delay in getting back to you on this. It slipped through the cracks, but we have now had a chance to double check what works and what doesn't. 
The only way we were able to replicate this was to have a document type without any properties. It works the same way as a normal Umbraco site does (have tested with the latest 8.6 on cloud). If you create a content template for a document type with properties it works as expected, you can edit the content template, filling in default values and use it to create content items which will have those values.

So I'm wondering if the main issue here is around not being to create a "Folder" content template, because it doesn't contain any properties? Either way, this is not possible, but if you want the folder you could simply add a text field property to it and it work as any other content template.

**Comment by benmccallum** [comment]
Thanks for the detailed answer. I got here due to the same problem and I was indeed interpreting this feature as being a template for a tree :) Would be a nice feature :P
