### ISSUE TITLE
📮 Feature request: Please add resource graphs to the Umbraco Cloud dashboard

### ISSUE THREAD

**Issue by jameswilki** [umbraco/Umbraco.Cloud.Issues#224]
As an Azure portal user, it would be really useful to see metrics for Umbraco Cloud sites from the dashboard. Useful graphs could include:
- CPU Time
- Memory working set
- Response time
- Data in
- Data out

Thanks, and kind regards,

James.

**Comment by c9mbundy** [comment]
I'd like to see some stats on the usage-limits that are apparently now being applied as hard instead of the previous recommended i.e. Node-count, PageViews-per-month. Media-Storage, Bandwidth-per-month, Custom-Domains. 

If Umbraco is now going to make these hard limits and force clients to migrate to higher plans when exceeded, then those stats need to be reviewable so that appropriate maintenance can be implemented where appropriate. It's bad enough that the rules get changed after a site has been launched, but having no obvious way to monitor such factors is not good. 

I'd also like to see a clear definition of what those limits are -- e.g. what *exactly* is the definition of a 'node' in the context of usage? - but that's a separate discussion.

**Comment by nul800sebastiaan** [comment]
Thanks for the request @jameswilki! 

We'd love to do that but at this point our infrastructure does not allow for such a detailed overview. We're moving to a new infrastructure hopefully by the end of the year where these kinds of insights are a possibility.

I've put this feature request on the ideas list for now for when we can provide this functionality. 

@c9mbundy - if you need more information on that, you can chat with support on the Cloud portal, I don't have an answer for that for you I'm afraid.

**Comment by jameswilki** [comment]
That's great. Thanks @nul800sebastiaan

**Comment by sajumb** [comment]
We have added the "Availability & Performance" page, where you can see most of the metrics listed above. In case, of the new for more metrics, please reach out and we will put it into the backlog.
