### ISSUE TITLE
Linking directly to a Media item

### ISSUE THREAD

**Issue by dalyUSN** [umbraco/Umbraco.Cloud.Issues#238]
We created content on our Development environment and linked directly to a Media item using the node picker. We saved and published this content, however, it was not viewable on the frontend of our site. 

<img width="1511" alt="Linked direct to Media item" src="https://user-images.githubusercontent.com/24275922/89201753-e2d4af00-d5a9-11ea-8062-21bc966c25bd.png">

We then copied the URL to the Media item and instead pasted that into the link picker. This method did display the Media item on the frontend. 

<img width="1516" alt="Copy and pasted link to Media item" src="https://user-images.githubusercontent.com/24275922/89201866-0861b880-d5aa-11ea-9a0f-0805c6cf05ad.png">

Here is what a user sees on the frontend of **Development Environment on Umbraco Cloud**.

<img width="923" alt="Frontend Development" src="https://user-images.githubusercontent.com/24275922/89201886-0f88c680-d5aa-11ea-9230-3c911c00b85a.png">

We then restored the content to our Local environment. The Media item that we had linked to was viewable on the frontend of our Local environment. 

Here is what a user sees on the frontend of **Local Environment on my machine**.

<img width="918" alt="After content restore Frontend Local" src="https://user-images.githubusercontent.com/24275922/89201986-36df9380-d5aa-11ea-9c6c-067cdde522e6.png">

Back office on **Development & Local Environments**
<img width="1517" alt="Back office Development   Local" src="https://user-images.githubusercontent.com/24275922/89201900-16afd480-d5aa-11ea-9148-1a245cfc4b7a.png">

The content in the back office and code for both **Local and Development environments** are the exact same. However, what is displayed on the frontend is different.

I spoke directly with Dennis on support about this issue, he tested it and got the same outcome. He then asked me to add it here. 

Thanks.

**Comment by nul800sebastiaan** [comment]
The problem here is that first thing you mentioned: 

>  We saved and published this content, however, it was not viewable on the frontend of our site. 

That is the part the you should look into instead of working around it. Only by selecting the media item in the picker properly will the value be saved in a way that can be converted across environments.

The feature where you enter a link in the text field will only ever transfer the literal link you put in there and that is expected behavior which will not change.

I'll close this issue and advise you to investigate why your media picker is not returning the correct media links for you. If you need some help with that, our friendly community at https://our.umbraco.com is a good starting point for asking questions about that!
