### ISSUE TITLE
Nested content does not get restored

### ISSUE THREAD

**Issue by deekoulos** [umbraco/Umbraco.Cloud.Issues#239]
Hey Guys,

using Umbraco 8.6.3 for a site hosted on umbraco cloud I am facing an issue regarding restoring of nested content. 

Steps to reproduce:

1. Create an element type containing one text string property type
2. assign the element type to a new data type with a nested content property editor
3. assign the data type containing the element type to a document type
4. create a content node of that document type in your dev, or live environment
5. add a test string into the property type of the element type within the created content node
6. save and publish
7. pull the changes to your local environment
8. do a content restore
9. Check the results

Expected Result:
The nested content is getting restored

Actual Result:
It is not.

All other content types which are not nested do get restored properly.

**Comment by deekoulos** [comment]
Hey @nul800sebastiaan 

could you reproduce this? It would be great to know, if this is gonna be fixed within the next updates.

Thanks
Dee

**Comment by nul800sebastiaan** [comment]
Hi @deekoulos! I was a little delayed on trying to repro this one, it sounds odd since many people seem to use nested content very successfully on Cloud.

I am sorry to disappoint but I have successfully gone through the steps above and on my local environment all the NC values came through. Let us know if you have more specific steps to reproduce, there seems to be some subtle difference for you that I don't have. 

Element type
![image](https://user-images.githubusercontent.com/304656/90248951-e550c780-de39-11ea-912b-e6f1c6bca939.png)

On the home doctype
![image](https://user-images.githubusercontent.com/304656/90248939-e255d700-de39-11ea-876c-e7f377d6417c.png)

Local gets the content from live
![image](https://user-images.githubusercontent.com/304656/90248954-e71a8b00-de39-11ea-9951-0e176a71528b.png)
