### ISSUE TITLE
Mark content as environment specific

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco.Cloud.Issues#264]
Marking specific content as forexample, dev content.

The use case would be if you have an instagram id on live but on dev you have development one for testing, if you content transfer from dev it would end up overwritting the one on live.

Can be ofcourse extended to other 3 party services aswell.

**Comment by sitereactor** [comment]
Maybe a better approach would be a way to store keys in the database (key value), which can be referenced from content. You could probably do some something like this with Dictionary items, but here the idea would be that the key/value is specific to the current environment and not something that is transferred between environments.

Similar to what you can do with appsettings on Azure App Service, but for content instead of code 🙂

**Comment by hfloyd** [comment]
@Frost117 - If you can use the web.config for this info, rather than a content node, it is easy to change it between Environments via web.config transforms. 

I can also think of some ways to create this sort of functionality in the back-office, using a "Settings" section in the Content tree. I think adding this sort of complexity to the Core functionality isn't really necessary.

**Comment by hfloyd** [comment]
Ps. I found this an interesting problem, so I wrote a little [article about how I would solve it in an implementation](https://heatherfloyd.com/blog/posts/3-ways-to-handle-environment-specific-data-in-an-umbraco-site/?ref=GitHubIssue), in case anyone wants some ideas.
