### ISSUE TITLE
Heartcore: Webhook not triggered on "Publish with descendants"

### ISSUE THREAD

**Issue by joakimmillen** [umbraco/Umbraco.Cloud.Issues#278]
When adding a webhook that should trigger on publishing of data it does not trigger when i select the "publish with descendants" option.

Reproduction
------------

1. Add a tree of content with random content types.
2. Add a webhook to a URI where you can see the amount of times the webhook has been called.
3. Go to the content and select "Publish with descendants" on the top content node.

### Bug summary

The problem is that the webhook is not called.

### Expected result

Expected the webhook to be triggered

### Actual result

It did not trigger the webhook.

**Comment by nul800sebastiaan** [comment]
Thanks @joakimmillen - it's probably due to this bug: https://github.com/umbraco/Umbraco-CMS/issues/9167

**Comment by sitereactor** [comment]
We should have this fixed in Heartcore as part of an upcoming update where we introduce "webhooks v2".

I will keep you posted on the roll-out.

**Comment by sitereactor** [comment]
We have rolled out webhooks v2, which is the default for all new Projects. This updated version is now part of our Content Delivery Platform and able to trigger webhooks for descendants.

You can reach out to Support via the Chat option in the Umbraco Cloud Portal and ask them about the option to be moved to "webhooks v2". It contains breaking changes from the original webhooks implementation, which is why we added it as v2 for new projects only.
