### ISSUE TITLE
Updating files in media library gives new urls 

### ISSUE THREAD

**Issue by Aaen** [umbraco/Umbraco.Cloud.Issues#292]
A brief description of the issue goes here.

The issue here is when you e.g have a link to a pdf in the media library and want to update this one to a new version your new pdf file will have a new link and you need to make a redirect from the old URL to the new URL 

## Umbraco version

Umbraco 8.9.1 

### Steps to reproduce
1. Upload a file in the media library
2. Remove the file from the node (Don´t delete the node in the media library)
3. Chose a new file
4. Now you will see that the URL is another one than the old one.

### Expected result
I would expect that the URL will stay the same 

### Actual result
Now you will see that the URL is another one than the old one.

**Comment by ronaldbarendse** [comment]
@Aaen If you're using Azure Blob Storage for media (that's now the default on Umbraco Cloud), the `Umbraco.Cloud.StorageProviders.AzureBlob.dll` assembly contained a custom `DateTimeMediaPathScheme` in version 3.0.3.

This would change the default `IMediaPathScheme` that generated media folders based on content/property GUIDs (that don't change and are therefore predictable) to one that was based on the current time (ticks in hexadecimal), which would result in a different folder name each time you save a media file.

It looks like this is removed in version 3.0.4, so it should now generate the same folder names again. If the current folder was generated based on the time, it would change again once, but stay consistent after that 👍🏻

**Comment by thebuilder** [comment]
Having immutable urls for media items is the right approach, since it allows for longterm caching of CDN assets.

This sounds more like it's an issue with the Link not getting the updated URL of the referenced media element?

**Comment by ronaldbarendse** [comment]
@thebuilder Not if you're updating/changing the file and want to make sure everyone sees the change, that's why Umbraco adds a cache buster value (based on the file's update date) to the query string of cropped image URLs: https://github.com/umbraco/Umbraco-CMS/blob/2bfef741914297c802bc6c77cc48780d7534f920/src/Umbraco.Web/ImageCropperTemplateCoreExtensions.cs#L123

But I agree Umbraco shouldn't change the media URL/folder name when you update the file with the same name.

If you want to automatically redirect old media URLs to the new one, this is possible with Skybrud Redirects using code similar to this (might require updating for Umbraco 8 though): https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/36.

**Comment by ktzanoulinos** [comment]
> Thanks again @ktzanoulinos - I wasn't aware that this was a Cloud site. I've talked to one of our developers there and it appears that this is a feature that was introduced to make sure that new uploads wouldn't get cached wrong. I'll re-open this and move it to the Cloud issue tracker. The team is probably going to disable the new blob storage provider for now until we can fix this specific issue.

Hello, do you have an update on this issue?

**Comment by sitereactor** [comment]
A fix for this has been rolled out and was part of version 3.0.4 of the Blob Storage Provider.
