### ISSUE TITLE
Deletion of data types and document types not deployed

### ISSUE THREAD

**Issue by AllanKirk** [umbraco/Umbraco.Cloud.Issues#302]
If I have a data type or document type on all my environments, but decide to delete it, that deletion is not deployed.

This is not an immediate problem, but it means the environments are not in sync, and that if I decide to create a similar data type or document type later, I might have a problem.

IMO, environments should be in sync.

Right now I manually remove the data types and document types on all environments after deployment.

**Comment by nul800sebastiaan** [comment]
Thanks @AllanKirk - this is expected behavior as we do not delete schema changes by default. A deletion should be a concious choice as it is not reversable, deleting a datatype will also delete all of the associated content. If that was an accident there would be no way to recover the content. So in the case of certain deletions we require you to manually delete the same items in the next environments.

You can read more about what we do and don't delete in this docs article: https://our.umbraco.com/documentation/Umbraco-Cloud/Deployment/Deploying-Deletions/
