### ISSUE TITLE
Invite member is always administrator

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Cloud.Issues#308]
If I add a member from organisation to a project on cloud the umbraco user always has admin rights.
This means I have to log into Umbraco evry time to change user rights.

It seems logical that a user is added with lower rights and can be elevated to admin and I think that was the case before?

**Comment by RyuLindow** [comment]
Hey, @FransdeJong.

Just to confirm, are you talking about users added via the "invite member" feature on the Cloud portal?

Those users will always have the admin rights on the backoffice which is a default setting. This is because users added on the project level have higher permissions than those added only to the backoffice.

**Comment by FransdeJong** [comment]
That's what I'm talking about. II think it is strange to automaticly make them admin.
We only ever create cloud members instead of backoffice users becasue it's easier when we add a stage environment.
What we don't want is add clients as admin to the projects.

The flow now is:
- invite cloud member to the project
- Check if they logged in
- Change rights to editor

It seems that it would logic to add all members as editor unless we specify it differently.

**Comment by nul800sebastiaan** [comment]
Hi @FransdeJong! This indeed has worked this way from day 1 in Cloud. I was going to ask about the reasoning behind this workflow and realized it after reading this:

> We only ever create cloud members instead of backoffice users becasue it's easier when we add a stage environment.

I was under the impression that users also get created when adding a new environment, but I guess that doesn't happen automatically. This is likely for good reasons, wouldn't want to inadvertently give too much access to someone, so it has to be a deliberate choice.

I do recognize that this becomes painful when adding many users or having to add them often. 

The feature request as such is a pretty good idea but we'd also need to query the actual site to know which user groups are available before we can add users to them. 

Additionally, I should remind you that giving people access to the cloud portal does also give them quite a few permissions in the portal that they probably should not have.

I'll need to ask around a little more about a way to more easily add users in specific roles, I'll get back to you.

**Comment by FransdeJong** [comment]
Thanks for the answer!
We have clients running multiple sites with us, so the portal is a great solution for them.

It would be great if we could think of a solution. Don't hesitate to contact me if you need any help thinking of a solution.

**Comment by nul800sebastiaan** [comment]
Thanks @FransdeJong! I have asked around, this is definitely a feature we anticipate building when we're building out UmbracoId some more. Right now we don't have a good estimate on when that can happen but I understand it's pretty high on the list. I'll let them know you're happy to validate the feature when we get a chance to put some more work into it, thanks!

**Comment by sajumb** [comment]
We are (better late than never) considering this feature request. In the current sprint we are handling a related feature request of specifying the specific project roles of the invitee for each environment in the project invite. Currently it is only possible to select the user to get the admin or the write role which then will be applied for every environment. We expected the update for project roles to be released within the next two weeks.

Hereafter we will provide the feature of specifying the backoffice user group memberships for each environment of the project in the project invite. We expect this feature to be delivered late January/early February.

**Comment by callumbwhyte** [comment]
@sajumb I came here to request this exact feature, sounds like you're already on it!

Sadly since the introduction of Umbraco ID it's not possible to use the workaround @FransdeJong discussed above - while users can be invited from the backoffice, I don't believe they can actually login... All they see is a "login with Umbraco" button, no username / password fields...

We currently have to invite all of our editors / read only backoffice users via the Umbraco Cloud portal, which means their users are created in the CMS within the "Admin" role - they then have access to code, settings, etc, we don't want them to have! This is made worse by the fact the user doesn't show in the backoffice until after their first login, meaning we have to continually checked they've logged in once (as an admin 😬) in order to assign them their correct role.

In an ideal world we should be able to assign backoffice user groups (including custom ones) directly in the invite flow + portal.

A temporary option that is certainly better than nothing could be:

- If the user has Cloud "Admin" permissions, put them in the "Administrators" user group
- If the user has Cloud "Write" permissions, put them in the "Editors" user group
- If the user has Cloud "Read" or "No Access" permissions, put them in the "Writers" user group

By default the "Writers" user group has no rights to public any content, so is effectively a read only user.

Thanks!

**Comment by FransdeJong** [comment]
@callumbwhyte I can agree with your proposed solution but what if the default user groups are removed?

I would prefer a solution where the usergroups are collected from the backoffice per environment and one or more can be handpicked. That would be the ultimate solution.

**Comment by sajumb** [comment]
Hi @callumbwhyte and @FransdeJong.
Thanks for your comments and suggestions. They are valuable and appreciated.

We have big ambitions with the portal handling of backoffice user groups in the portal. The original concept of automatically assigning an admin backoffice user group to a new portal user assigned to a portal project is surely outdated. We see that agencies invite various personas/users to projects that should definitely now have the backoffice admin. We naturally want to support that workflow the best possible way.

Initially, we will go with a solution where the user in the project invite dialog is presented for all the actual environment-specific backoffice user groups. As you both know these can potentially vary from project to project and even environment to environment. Our intention was to have this feature done later this week, but we have recognized that we have to rework some of the integration code for assigning backoffice user groups from the portal. When this refactoring has been completed we will start added support for better backoffice user group handling in project invites. We will strive to complete this in February but cannot give a precise release date just yet.

We are currently looking into always displaying the actual user groups for backoffice user in the project edit team page. When this and the project invite has been covered, we will consider what will give you the most value to look on next. It could very well be the option to change backoffice user groups from the portal. But let us stay in touch as the work progresses, so we are sure that we cover your requirements and expectations for handling backoffice user groups in the portal. I will reach out when input is needed. Thanks again.

**Comment by sajumb** [comment]
The project invite dialog now has the option for the user to specify the backoffice user group for the invitee as requested. See the latest releasenotes page for more info: https://our.umbraco.com/documentation/Umbraco-Cloud/release-notes/2022-03-02-ReleaseNotes
