### ISSUE TITLE
Add full solution repo on Cloud

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Cloud.Issues#312]
It would be great if we could have the full solution repo on cloud.

At the moment we have to live with two separate git repo's. One being the "Core project" with the solution and everything and the other being the web project containing the cloud site.
It would be great if we just don't need to deal with this anymore.

I know some agencies get around this by storing everything in their own repo and building a web project that they push to cloud. This is a option but it feels way to complicated for a agency that has Umbraco Cloud as primary hosting solution.

Would this be technically possible?
Would this be something HQ is willing to investigate?
Is there anything we can do to help investigating?

What I'm not looking for is updating packages in the custom code.
What I am looking for is a way so have custom code and web code in branches together so we can work on features without running the risk of core and web getting out of sync.

Frans

**Comment by sitereactor** [comment]
We have a few ideas for improving the Deployment flow for projects with solution, etc on github/AzDevOps/other.

One approach would be to connect your github repository to your Cloud Project and we will handle the rest => build + deploy to Cloud. And with Pull Requests back to the repository with updates.

When we are a bit further with our new infrastructure setup, I can share more.

**Comment by FransdeJong** [comment]
Great to hear!

**Comment by ronaldbarendse** [comment]
There's already some work done and documentation available on how to setup your own repository and deploy that to Cloud:
- https://github.com/umbraco/vsts-uaas-deploy-task
- https://shazwazza.com/post/web-application-projects-with-umbraco-cloud/

The biggest issue is keeping your own repository in-sync with the automatic updates/patches done on Cloud. Even if changes on Cloud creates PRs to pull those back into the 'source' repository, this would result in issues with NuGet (as this still requires the packages.config and updates can one be done in Visual Studio).

Another issue is the possibility of overwriting changes in Cloud with your own build, causing downgrades (which aren't supported, as the database structure can only be upgraded). Because database changes are only shipped in minor versions, this shouldn't be a problem with the automatic patches though (as long as you don't upgrade to a newer minor version on Cloud without upgrading to the same version your own repository). This could be prevented by blocking the deployment if higher versions of certain assemblies are found.

And lastly, not all code on Umbraco Cloud projects are available as NuGet packages (Umbraco Deploy is available on a MyGet feed). The assemblies, config files and plugin files for Azure Blob Storage and Umbraco ID aren't available yet, making the custom repository/build workflow very inconvenient!

**Comment by FransdeJong** [comment]
@ronaldbarendse
Thanks for mentioning that solution. I've seen that but that just feels wrong for me.
I'd like a native solution without all the drawbacks you mention above.

In a perfect world I can branche my core and web project in sync on a cloud repository to work on updates without losing all the benefits that Cloud brings us. Untill then I'll be using the 2 repo solution. Feels less hacky in my opinion.

**Comment by sitereactor** [comment]
The challenges with the current solutions are still that its all one way. The missing piece to the puzzle is pushing updates back to you and your repositories.
We have two big items on the roadmap for the next ~ 6 months with Cloud vNext (new infrastructure) and expanding to new regions. After that I am quite positive that this ci/cd, developer experience and solution/repository setup is next on the list. Everyone on the team is quite excited about improving this area and i would br happy to include those who are interested to give feedback early on.

The missing packages will definitely be addressed as part of this. The initial reason for not releasing the blob storage package was that we didn't want to give out the wrong idea of replacing existing community packages, because that wasn't the intention. The one we created is for Cloud only and that can be a bit challenging to communicate via nuget.

**Comment by FransdeJong** [comment]
Sounds great! I'm so looking forward to a great solution in this flow.

**Comment by ronaldbarendse** [comment]
Most updates could be pushed back using patch files (`git format-patch` on the Cloud repository and `git apply` on your own repository), which would be great to keep Deploy artifacts (`data/revision/*.uda`), config files, etc. in sync.

Conflicts could be reduced by doing a [three-way merge](https://git-scm.com/docs/git-apply#Documentation/git-apply.txt--3), so the conflict markers can be committed to a PR that can be manually fixed when merging the changes back.

Any changes to NuGet packages will currently need manual steps to apply the required changes (file copies, config transforms, updated assembly reference paths in the project file, etc.), although supporting SDK-projects for website projects would allow simply changing the version in the `PackageReference`, applying any further changes (e.g. updating the `Umbraco.Core.ConfigurationStatus` or CDF version) and deploying the build: https://github.com/umbraco/Umbraco-CMS/issues/3635.

@sitereactor I've already made internal NuGet packages that contain the required dependencies (`Serilog.Sinks.MSSqlServer` and `WindowsAzure.Storage`), XDT transforms, assemblies and plugin files (`App_Plugins\UmbracoId`). Having to update those packages for every update is a chore though, but beats manually the copying files on every project, fixing assembly redirects, project reference paths, etc.

**Comment by danlister** [comment]
Hey @FransdeJong 👋🏻 

Since the release of v9 projects on Umbraco Cloud, customers can now store any solution files and projects in the Cloud repository. This should streamline your workflow and address the concerns mentioned. If you think there's something we missed, please feel free to re-open the issue. If you have any further feedback or questions, let us know.
