### ISSUE TITLE
FYI - Issues caused by datacenter URL changes

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Cloud.Issues#410]
### Issue description

Some of my clients' sites just switched to the new datacenter, changing their access URLs from 
`https://PROJECT.s1.umbraco.io` to `https://PROJECT.euwest01.umbraco.io/`

I'm glad to see your infrastructure plans are moving ahead, but I think there are a few issues with the transition process you could improve.

1. There were no communications about the URL change - no warning emails or post-change emails went out. I had my clients coming to me saying "why is the dev site offline?" when they couldn't access it via their usual URL.
2. When a site gets changed, to keep things seamless, you should also make sure to update the `\Config\UmbracoDeploy.config` file. Right now trying to restore from dev to local is giving an error message:
```
An error occurred
The source environment has thrown a Umbraco.Deploy.Exceptions.RemoteApiException with message: The remote API is not accessible, getting a 403 error connecting to https://dev-PROJECT.s1.umbraco.io/umbraco/backoffice/Deploy/Environment/BeginSession It might have been caused by an inner with message: (empty)
```
I updated the file locally, and the Restore was able to complete.

**Comment by RyuLindow** [comment]
Heya Heather.

Sorry to hear that it wasn't communicated over email :(

I'll follow up on that on Tuesday at the team meeting because this isn't okay...

We got these docs about the post-migration changes, though. Take a look here - https://our.umbraco.com/Documentation/Umbraco-Cloud/Upgrades/Migrating-To-New-Infrastructure/#after-the-migration

Regarding the `\Config\UmbracoDeploy.config`, which line was incorrect?

Line 2 where you have `https://www.s1.umbraco.io/project/{projectAlias}` is correct, so assume that it was one of the next lines that being with `environment type=`. Am I correct?

Were they still saying s1 instead of euwest01?

I've just cloned a site which was migrated and changed euwest01 back to s1 in the `<environment type="development"` line and then tried to restore content dev>local.

It resulted in:
```
Umbraco.Deploy.Exceptions.RemoteApiException with message: The remote API is not accessible, getting a 403 error connecting to https://dev-{projectAlias}.s1.umbraco.io/umbraco/backoffice/Deploy/Environment/BeginSession It might have been caused by an inner with message: (empty)
```
which is the same error are yours. Changing it back to euwest01 resolves the issue.

Will have to keep an eye out for this one because I've checked several projects which got migrated and all of them had the correct URLs in the deploy.config file 🤔

**Comment by hfloyd** [comment]
Hi @RyuLindow , 

Yes. the lines were the ones for each of the specific environments. The URLs were still listing "s1". I just updated those, and the Restore then worked fine. I've pushed the change up to the repo for the other devs on the project.

My other client who got the new URL last week did have an updated config file, so it isn't consistently a failure... part of my reason for posting was to create a searchable record for anyone else coming across the error - so they'd have a quick fix. 

Thanks for bringing up the lack of email communications with the wider team. I think that will help anyone else who is getting caught off-guard.

**Comment by RyuLindow** [comment]
Thanks for the confirmation, @hfloyd.

I'll speak with DevOps about the URL issue. It's worth investigating 👍

**Comment by hfloyd** [comment]
Ps. I took a look a the post-migration docs you referenced, Darek, and it mentioned an updated git URL.:
![image](https://user-images.githubusercontent.com/1252593/125999056-5f4ef13d-4d6b-4cfb-88d5-291d63af2c26.png)

...but checking in the Portal (Development > Clone Project) I still see `https://dev-PROJECT.euwest01.umbraco.io/eb1d42de-4069-4cfe-ad40-aae67841361e.git` Should that have changed?

**Comment by RyuLindow** [comment]
Yeah, so that's another miscommunication..
I've asked for the date to be removed/changed, as the feature isn't out yet and we have no specific ETA but it seems like it hasn't been done. Sorry again :(

Made a PR to docs just now to get this updated :)

**Comment by RyuLindow** [comment]
And it's live, @hfloyd 

Thanks for pointing it out to me :)

**Comment by RyuLindow** [comment]
Heya, @hfloyd 

Checked with the team today.

We've mailed all technical contacts on the projects and linked to this blog article - https://umbraco.com/blog/status-on-new-umbraco-cloud-infrastructure-april-2021/

If you're not listed as a technical contact then you wouldn't get it.

**Comment by hfloyd** [comment]
Thanks for the info, @RyuLindow. I **AM** listed on the "Technical contacts" list for both the projects which recently were updated, I did receive some emails awhile ago along the lines of "your sites will be updated soon" - then a few "we were unable to update your site" messages. 
Perhaps this is the communications you are talking about.

I guess my suggestion would be that right after a site has been migrated, a simple email would go out to **ALL** users who have access to dev/staging environments which just says:

"We have moved your project to  our new data center. You can access the portal at the same Url - https://www.s1.umbraco.io/project/PROJECT, but your development environment url has changed to https://dev-PROJECT.euwest01.umbraco.io/ ... For more information about this change, see: [docs/blogpost/whatever]"

**Comment by RyuLindow** [comment]
That's a good suggestion. I'll bring it up at the meeting tomorrow to discuss it :)

**Comment by greystate** [comment]
Now, about 16 project migrations later, I can say that by far the worst part is that we're not able to put a permanent redirect in place for the URL change. Or that Umbraco hasn't automatically provided one.

Only about 10% of clients actually understand what happens - and only 1 or 2 percent of those can figure out how to use the new link (or change the bookmark).

**Comment by sitereactor** [comment]
@greystate I really wish it was possible, but unfortunately we were/are in a bit of a pickle with regards to the old s1 hostname.
If we added this hostname to Cloudflare in order for us to redirect certain internal hostnames ie. `my-project.s1.umbraco.io` to `my-project.euwest01.umbraco.io` we would immediately break any custom hostname that used the internal s1 hostname as a CNAME.

When we reach a critical mass for hostname DNS being updated to use Cloudflare we can enable a redirect from s1 to euwest01, which should be fairly soon.

I can only apologize for this friction. If it was possible to create a redirect without breaking other things we certainly would have done so. We were able to do this with the SCM/git hostname, because this didn't pose the same kind of challenge. Maybe you haven't noticed, but both `my-project.scm.s1.umbraco.io/<guid>.git` and `my-project.scm.euwest01.umbraco.io/<guid>.git` works when cloning/pulling/pushing.

**Comment by greystate** [comment]
Thanks @sitereactor — I really appreciate it 👍 

It goes without saying that me using "worst" to describe it here really means it's the only client-facing problem, so therefore it's automatically multiplied in severeness — the Git URLs and deploy configs etc. are all things we can fix behind the scenes, and this just _seemed_ so overlooked.

**Comment by sajumb** [comment]
This issue was originally related to the migration to the new app service infrastructure. It seems like every question has been answered, so we are closing this issue.
