### ISSUE TITLE
DNS Settings for cloud sites

### ISSUE THREAD

**Issue by niekvanderreest** [umbraco/Umbraco.Cloud.Issues#426]
### Issue description

Hi all,

I've run into an issue with a DNS admin that refused to change settings for a domain to point to dns.umbraco.io via CNAME as suggested to do by the cloud documentation at: https://our.umbraco.com/documentation/Umbraco-Cloud/set-up/Manage-Hostnames/ 

He was right to do so because it might cause problems with other DNS settings (MX, txt, ect). Howerver pointing to an IP via A record can cause the site to go offline due to an IP change on cloud.

The problem has been "fixed" inhouse in a hacky way but I would prefer Umbraco find a sollution for this and/or add additional recommendations to the documentation as it's quite common for the root domain to point towards a website.

Any ideas on this?

**Comment by sitereactor** [comment]
This sounds unusual. Was it a wildcard record you tried to set up via a CNAME?

For a-record you can usually add a low TTL to improve the switch to the new origin.

When you add the hostname via Umbraco Cloud its setup immediately, but the certificate won't be issued until the record has been verified. It's usually fairly quick, but beyond that there is not much we can do when its a new domain.
When its an existing hostname (on Umbraco Cloud) its already been verified and prepared, so the switch will be instant - apart from the DNS propagation, which we can't really do anything about.

**Comment by niekvanderreest** [comment]
It wasn't a wildcard record, the CNAME can't be set for 'mydomain.com' because the DNS admin claims setting a CNAME on the root domain will cause problems for other DNS records such as MX and txt records. For this reason currently only the www. domain is set up with a CNAME to dns.umbraco.io.

(some googling seems to verify that although I'm no DNS pro). I couldn't find any documentation only the warning:
![image](https://user-images.githubusercontent.com/28493458/130408932-ed7b7519-1f56-4c4d-913d-044c8ee7f7f4.png)

 I'd guess that making a site available under root domain is a very common use case, maybe I'm missing something and adding a CNAME won't break any records.

> For a-record you can usually add a low TTL to improve the switch to the new origin.

So the usual way to do this is point the domain via A record en update it a.s.a.p. when/if the IP of Cloud changes and the site goes down?

I get that DNS settings at provider level are technically out of scope but this sounds less than ideal.

**Comment by c9mbundy** [comment]
Just one data-point, but I have a bunch of UC sites running with CNAME on www and A record on the root, I haven't encountered an issue. Obviously, the UC infrastructure *can* change, but when I asked about this point I was assured that any changes would be rare and well flagged in advance.

**Comment by sitereactor** [comment]
Let me try to address the questions by explaining why we have that warning in the documentation.
First off, we always recommend using a CNAME record when possible, because it relies on a hostname and not a single Public IP. We do know that some people will want the root domain as a hostname on their Umbraco Cloud website and that not all DNS Providers allows setting up a CNAME record for the root domain. So far I have only come across Cloudflare as a DNS Provider who allows this. So when you want to use the root domain as a hostname, setting up an A-record is a perfectly valid option and we provide two Public IPs that can be used for this purpose.

If, at some point in the future, one of these Public IPs need to be changed, we will advertise it well in advance. I do believe its highly unlikely that this will happen, but as it might happen we have to make that obvious to everyone using Umbraco Cloud.

Any hostname, regardless of it being a CNAME record or an A-record, will need to propogate (the changes) before the DNS record and thus the hostname is globally available. Usually CNAME records are a bit faster than A-records, but its also very common to set a low TTL on the hostnames that needs to be added or changed ahead of time, so the update happens a bit faster than usual. Once its live, the TTL can be changed back to the default.
You can use something like [https://dnschecker.org/](https://dnschecker.org/) to follow the global update of the hostname and the origin its pointing to.

Hope this helps the understanding of the two approaches to setting a hostname.
