### ISSUE TITLE
ImageProcessor exception

### ISSUE THREAD

**Issue by Ramya-Devendiran** [umbraco/Umbraco.Cloud.Issues#490]
### Issue description

Since our project deployed live in cloud, the below error is logged multiple times a day on different image url. The website is UP and running normally. Umbraco version - 8.11.2 
Error: ImageProcessor exception: ProcessImageAsync 559 : The request /image/xxx.jpeg?fh=640&fw=640 could not be understood by the server due to malformed syntax.

No such errors are logged in the cloud dev environment.

I notice that the imagefolderid path is missing in the url tagged in the error message. for ex. c2fbg3kx is missing in the url - /media/c2fbg3kx/xxx.jpg

The images appears in the webpage correctly.
![Screenshot_8](https://user-images.githubusercontent.com/82824097/140737434-9fbacbc6-0a9e-45e7-b07a-903617e33796.png)

**Comment by bjornnorlen** [comment]
@Ramya-Devendiran Did you find a solution to this issue? Several of our clients experience the same issue on latest version of Umbraco 8. We also receive issues on the form "ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 610 : No image exists at D:\home\site\wwwroot\media\1234\name-of-image.jpg". There is no image with that name in the folder 1234 but in 1235 there is. Does it have anything to do with the legacy media picker field?

**Comment by Sven883** [comment]
@Ramya-Devendiran we have the same problem. Did you find a solution for this?

**Comment by RyuLindow** [comment]
Which version of https://www.nuget.org/packages/Umbraco.Cloud.StorageProviders.AzureBlob are you using?

**Comment by Sven883** [comment]
Hey @RyuLindow, we're not using that package. Our website is self-hosted on azure.

**Comment by RyuLindow** [comment]
Ah, in that case, I'm not sure if this thread is relevant for you as projects on Umbraco Cloud our own blob storage package and this is the GH tracker for Umbraco Cloud.

You might want to look into upgrading your Umbraco/imageprocessor version and see if that helps. I would also advise looking on https://our.umbraco.com/forum/ or the CMS tracker :)

**Comment by Ramya-Devendiran** [comment]
> Which version of https://www.nuget.org/packages/Umbraco.Cloud.StorageProviders.AzureBlob are you using?

We are not using blob storage. We use the default PhysicalFileSystem storage.

**Comment by RyuLindow** [comment]
@Ramya-Devendiran
It's recommended that you have your media in blob storage on Cloud rather than in the physical file storage.

Reason are:
1. Better performance with blob storage
2. Physical storage limits as per: https://our.umbraco.com/Documentation/Umbraco-Cloud/Getting-Started/Umbraco-cloud-plans/#hard-quotas-for-shared-umbraco-cloud-plans

If you reach out to support, we can help you migrate your media to our blob storage, as part of your UC subscription :)

**Comment by bjornnorlen** [comment]
We're using the default PhysicalFileSystem as well. @Ramya-Devendiran did you try storing the media in blob storage and did it solve the problem?

**Comment by mclausen** [comment]
Howdy there 🤠

Looks like a lot of water has flowed under the bridge since the last update on this issue.

From what I can tell, this issue is not related to Umbraco Cloud. My recommendation is to open a new issue on the [CMS issue tracker](https://github.com/umbraco/Umbraco-CMS).

Sorry for the long wait and any inconvenience this might have caused.

Kind regards,
@mclausen, Cloud Platform/Core Team Lead

**Comment by arun-vr-official** [comment]
**Hi Team,**

I faced a similar issue:
`ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 610 : No image exists at E:\Webfiles\my-website\httpdocs\media\1061\load-web.jpg`

Unfortunately, I couldn't find the root cause, but I implemented some logging and configuration changes to suppress these errors and avoid unnecessary requests.

✅ **Web.config:**

```xml
<rule name="Block none existing image files before ImageProcessor" enabled="true" stopProcessing="true">
```

✅ **Serilog configuration (serilog.config in config folder)**

```xml
<!-- To avoid ImageProcessor error being logged-->
<add key="serilog:minimum-level:override:ImageProcessor.Web.HttpModules.ImageProcessingModule" value="Fatal" />
```

✅ **Serilog user configuration (serilog.user.config in config folder)**

```xml
<!-- To avoid ImageProcessor error -->
<add key="serilog:minimum-level:override:ImageProcessor.Web.HttpModules.ImageProcessingModule" value="Fatal" />
<add key="serilog:minimum-level:override:ImageProcessor.Web.HttpModules.ImageRequestModule" value="Fatal" />
<add key="serilog:using:FilterExpressions" value="Serilog.Filters.Expressions" />
<add key="serilog:filter:ByExcluding.expression" value="Contains(Message, 'ImageProcessor.Common.Exceptions.ImageProcessingException')" />
```

✅ **Other step**
Renamed `media\web.config` to `bkp-web`.

I'm still trying to figure out the option to avoid those requests

Thanks

**Comment by mclausen** [comment]
Hi @arun-vr-official and thank you for posting.

From what I can tell, this issue is not related to Umbraco Cloud. My recommendation is to open a new issue on the [CMS issue tracker](https://github.com/umbraco/Umbraco-CMS).
