### ISSUE TITLE
Deploying from development to live requires manual reload of Memory Cache to correct page routes

### ISSUE THREAD

**Issue by bill-dastardly** [umbraco/Umbraco.Cloud.Issues#494]
### Issue description

When deploying from Development to Live, any schema or code change, URLS below root end up unrouted and return 404's until an admin user manually triggers a Reload of the Memory Cache in the Live Backoffice

**Comment by RosenPetrov** [comment]
This is happening also on our solution. I don't know about the other solution, but I assume the issue is related to the amount of content we have on the site. We have a lot of content. For this reason, even the "echo > deploy" has to be run manually and a couple of times until it succeeds. (which is another issue)

**Comment by RyuLindow** [comment]
Hi there.

What version of Deploy are you using?

Also, could you give me steps to reproduce this issue?

**Comment by FransdeJong** [comment]
@RyuLindow 
Hi Darek,
I can confirm this still happens on every version of deploy on umbraco V8 (don't know if it still happens on V9) and in random fashion.
I have a long running issue over here:
https://github.com/umbraco/Umbraco.Cloud.Issues/issues/223

I think the only way to solve this issue is to always reload cache after deploy.

I suggest closing this issue and carying on in the other issue?

**Comment by sajumb** [comment]
I am closing this and we will instead consider the longer running issue at #223.
