### ISSUE TITLE
You can't query Eye Color Dropper Picker with Graphql

### ISSUE THREAD

**Issue by Hanskrogh** [umbraco/Umbraco.Cloud.Issues#527]
### Issue description

You can't query Eye Color Dropper Picker with Graphql, it is not generated in the schema....

---
_This item has been added to our backlog [AB#16702](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/16702)_

**Comment by sitereactor** [comment]
The Eye Color Picker was added in the last update and initial support was added to the REST API while GraphQL support was left until after the upgrade. We'll get GraphQL support added in the near future.
I'll see about adding it to our next sprint starting Monday next week.

**Comment by sitereactor** [comment]
@Hanskrogh the update, which enables GraphQL for the Eye Color Picker has now been deployed to Production.
For the document types, which use the Eye Color Picker you can re-save them in order to refresh the GraphQL schema. Once that is done you should be able to use it in your GraphQL queries and see it reflected in the GraphQL Playground in the Umbraco Backoffice.
