### ISSUE TITLE
Sites are going down with a 503

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Cloud.Issues#538]
### Issue description

I have had 2 sites on Umbraco Cloud going down with a 503 in the past 2 weeks.
It happens without us doing anything.

On this site the latest time I know it was still running was 03:37 tonight and just now I got a call from our client.
Nothing is in the log and our monitoring wasn't triggered at all.

A simple restart fixes the issue.

This is making me really nervous.

cc: @sajumb

**Comment by sajumb** [comment]
I am sorry to hear about the issues for the two Umbraco Cloud projects the last couple of weeks.
We will very much like to look into this.

I have sent you an email in order to get more insight and to coordinate with our support and/or black ops team if they aren't already handling this issue.

**Comment by FransdeJong** [comment]
@sajumb 
Is this issue solved? I understood from support that they couldn't find why this was happening and that more agencies have run into this issue.

**Comment by sajumb** [comment]
@FransdeJong You are partly right. During the first days of February we had a few (less than five afaik) reports with the same issue as reported by you. We believe that was due to an issue in the Azure infrastructure. Accordingly, we opened a ticket at Microsoft to look into this.

We believe that it has been sorted out. If you run into a similar issue, please report it instantly to our skilled support crew and we will natural escalate the issue to our 2nd level support.
