### ISSUE TITLE
Should Auto-upgrade delete deleted files from Umbraco?

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco.Cloud.Issues#54]
When the magic auto upgrade process runs, it leaves files that no longer is a part of Umbraco.

I just took our baseline (which I think was started at 7.5) and compared the folders Umbraco and Umbraco_Client with a freshly downloaded version of 7.13.2. There was over 1000 files missing in the fresh version (mostly aspx and ascx).

I did this because Visual Studio started acting up on those files because of missing types like `Could not load type: 'Umbraco.Web.UI.Umbraco.Controls.Images.ImageViewer'.

Shouldn't these files be removed automatically? Or can we end up having old solutions bloated with old files?

**Comment by nul800sebastiaan** [comment]
Yes, we do not delete files on purpose because you might still be using them. This may seem to be overly cautious on our part but that is because we have also seen crazy usages of the files that we would otherwise delete. So we've decided to not delete anything during upgrades unless it is critical (as in: if we don't delete file X, the site will not function at all any more).

You're, of course, welcome to clean up unused files if you don't need them any more. 👍
