### ISSUE TITLE
Feature Request: Monitoring Dashboard

### ISSUE THREAD

**Issue by c9mb** [umbraco/Umbraco.Cloud.Issues#544]
### Issue description

AzureWebApps provides monitoring data  which can be viewed from the Azure portal, but this information is not available to the Umbraco project portal.

I had a recent incident where one of my UC sites was behaving really poorly, and I couldn't work out what was going on  - it turned out to be a UC environment problem resulting in the site being starved of network connection, and causing high CPU% on the site.

Some insights into the site's performance would have been really useful in isolating the issue - code, configuration or environment.

They would also be useful in analyzing demand issues - if the site is undersized - and other alerts that something might need attention.

My understanding is that metrics are available as a JSON REST request, and so could be displayed on the project portal as a dashboard - perhaps even using embedded PowerBI.

**Comment by sitereactor** [comment]
We are talking about how we can expose these types of details in the Portal, but don't think there is a timeframe for it yet. Maybe @sajumb or @ksuvec can elaborate.

**Comment by sajumb** [comment]
Thanks for the request.
A monitoring dashboard is definitely something that is highly prioritized for us to add to the portal in the future. We are starting to deliver some relevant monitoring dashboard and the first thing will be listing the ressources causing the most bandwidth uses on the live environment. The first version of this is targeted in a fortnight from now. This is just the first step of many to show more detailed information for enabling developers to solve performance or stability issues that currently is hard due to the lack of the required information. We see a big potential in displayed this Azure monitoring data to our customers and are ambitions are quite high. 

We are currently creating an internal roadmap for the monitoring feature. In order to validate this plan and to have multiple perspectives included we would very much like to have a customer-centric approach with involvement of current cloud portal users. If you are interested in contributing with perspectives, ideas and requirements you are very much welcome to reach out to me. Any form of contribution is very welcome. My Umbraco initials are 'saj'.

**Comment by sajumb** [comment]
We have noted this feature request and will be considering it in the upcoming months. I will be closing this issue, as the request is considered. If you have any questions feel free to reach out to me.
