### ISSUE TITLE
Issue with sending invitations through environements on cloud

### ISSUE THREAD

**Issue by thejokerd3** [umbraco/Umbraco.Cloud.Issues#547]
### Issue description

There is an issue when inviting users to environements on cloud.

This issue occurs on V8 and V9 - it works the first time, but the second time the invite is not being sent. 

1. Invite a user in the staging environment; eg: [example@mail.dk](mailto :example@mail.dk)
2. Wait until you have received the invitation; (comes in at [example@mail.dk](mailto:example@mail.dk))
3. Copy the link from the invitation and place it in a private window;
4. Complete the account and log in to the back office of the staging. (so far so good)
5. Now go to the development environment \ live environment and invite the same user again [example@mail.dk](mailto:example@mail.dk);
6. Now you will not receive an invitation and that is not correct.

Darek can also confirm this behaviour - and he also checked sendgrid to verify that the second invite is not being sent.

**Comment by thejokerd3** [comment]
thejokerd3 == Muslim Al Ali from Umbraco HQ

**Comment by RyuLindow** [comment]
I've checked it both for a user which wasn't on Cloud prior to getting and invite and then for a user that already exists on Cloud.

The first one gets the Umbraco Id verification code(which is expected) and then one standard invite to the project mail.

The already existing user gets one standard project invite mail.

Perhaps, it's related to that mail flow change where the project invite has a link to https://www.s1.umbraco.io/profile/pendinginvites instead of the one that let you accept the invite directly from the mail.

**Comment by sajumb** [comment]
We are sorry that we currently only have provided a workaround and have not actually solved this issue. The workaround is shown [here](https://github.com/umbraco/Umbraco.Cloud.Issues/issues/582#:~:text=Until%20then%2C%20a-,workaround,-will%20be%20that). Things are starting to look brighter though. As we expect to have a fix ready for this issue in September. Feel free to contact our support or me directly if you have an issue with the workaround or have any questions regarding this issue. Once again sorry for the inconvenience.

**Comment by rachelsimonb** [comment]
Is there any update here? This is becoming a real issue for multiple projects and the workaround does not always work.

**Comment by sajumb** [comment]
I have talked with our Cloud engineers who own this functionality. They are motivated to consider it as soon as possible, but it is likely that the issue will not be resolved until the middle or end of the fourth quarter of this year.

Once again, we must apologize for the long wait for this issue to be resolved.

**Comment by sajumb** [comment]
An update. We are considering this bug in our two-weeks sprint that started today.

**Comment by sajumb** [comment]
I finally have some good news regarding the issue below. It is now possible to invite a user to several back offices in the same Umbraco Cloud project.

However, there is a small "but". Currently, the user will receive an incorrect email when invited to his second or third environment from the backoffice. That email will have the title "Umbraco Cloud - You've been invited to a project". Furthermore, there is a link to accept an invitation to a project in the Umbraco Cloud portal, which could confuse the reader of this email.

We will change the format of this email so that it is only notified that the recipient has been invited to a new back office and not a new project.

However, we think that this is a minor detail that should not prevent the release of the main bug fix. We recommend that for the time being you send an email notifying the user of the addition to a new back office and that he should ignore the received email with the title "Umbraco Cloud - You've been invited to a project".

We apologize for the unreasonably long wait for a solution to this issue.

I'll post a new update when an update to the mail template has been applied.

**Comment by sajumb** [comment]
This issue has been resolved.
