### ISSUE TITLE
User invite not sent to existing account holder

### ISSUE THREAD

**Issue by faizal2810** [umbraco/Umbraco.Cloud.Issues#582]
### Issue description

When an administrator sends out a user invite to the backoffice of any environment for any pre-existing user, the invite is not received.
For example, Ally Cardger is assigned as an editor in our staging site.

![image](https://user-images.githubusercontent.com/78047853/171230006-c73c5955-5ecd-433c-9dcf-5a4032216fa7.png)

2. Therefore Ally Cardger does not receive an invitation when sent from the live site.

![image](https://user-images.githubusercontent.com/78047853/171230395-24e59c5b-2dc4-451c-b36b-3d7f7c2c4c4e.png)

**Comment by sajumb** [comment]
Hi @faizal2810,
Thanks for reporting this. We are aware that there currently is an issue with inviting an existing backoffice user to a another environment in the same project when using Umbraco Cloud as you report. We will look into this issue really soon. And let you know when a fix has been deployed.

Until then, a workaround will be that you make the invite to user from the Umbraco Cloud Portal. As the email of the user already is coupled to the existing user, you will (unfortunately) have to use a new email when inviting the user to the backoffice.

This short demo illustrates an invite from the Umbraco Cloud portal to two backoffice environments (where the user in this example is added to the _Administrator_ backoffice user group)
![InviteUserToBackoffice](https://user-images.githubusercontent.com/93588665/171339871-4b700db6-1c40-4ce5-bbf8-79847aa251a4.gif)

Sorry for the inconvenience.

**Comment by Frost117** [comment]
Hi @sajumb 

After playing around with the invite flow I have found the following:

When you invite a new user to a Cloud project, and you only invite them through the backoffice on there dev env then they will have access to that the dev env.

Important thing to note here, the invite flow makes the user create their profile so it is available on Cloud aswell. 
So even though you invited the user to the backoffice that user also get access to the cloud portal itself.

Onward to the issue then, when I invited my new user to the project and invitation email got sent to the inbox, however the accept invitation does not arrive in the portal, because that user is already on the project. 

In the below screenshot you can see the flow of the invite:
![image](https://user-images.githubusercontent.com/32164310/171486846-ae0f4fa4-a724-46da-b1c2-10af13329e07.png)
1. User gets added to project via the backoffice - therefore it should not have access to do anything on the project page.
2. User is added correctly to the dev env as an admin, but not on live, which works fine.
3. User does noget get Update to have access on live, when invited through the backoffice, because an invite is not sent out for them to accept here:

![image](https://user-images.githubusercontent.com/32164310/171487252-e60f3c1c-7cfd-4e33-9ace-2f7daac69ea5.png)

**Comment by sajumb** [comment]
Hi @aguyfromdenmark 
We understand your frustration. The backoffice invite workflow should definitely work as simple as you have outlined. And in most scenarios it does work as smooth as that.

However the workflow currently has an issue when the person in step 1 already has a been invited to another environment in the **same** cloud project. And that is naturally something that we look into and solve as quickly to prevent further frustrations.

I know it is not ideal but you could consider the workaround with inviting the editors using a new email address (as described above) until the fix has been applied.

Sorry for the inconvenience.

**Comment by sajumb** [comment]
Hi @faizal2810,
We unfortunately don't have a more specific release date for the required bugfix. It is on the very top of our backlog and will hopefully be considered soon.

Please not that there is a workaround where you invite the user with another email address. Some mail providers like GMail enables you to add <email account><something>@<domain> like _orginal+backoffice@acme.org_ if you want the invitee to use the same email account. It is certainly not perfect but still a workaround that might be sufficiently until a fix is deployed.

Sorry for the inconvenience.

**Comment by sajumb** [comment]
We are sorry that we currently only have provided a workaround and not actually solved this issue. Things are starting to look brighter though. As we expect to have a fix ready for this issue in September. Feel free to contact our support or me directly if you have issue with the workaround or have any questions regarding this issue. Once again sorry for the inconvenience.

**Comment by sajumb** [comment]
An update. We are considering this bug in our two-weeks sprint that started today.

**Comment by sajumb** [comment]
An update has been posted here: https://github.com/umbraco/Umbraco.Cloud.Issues/issues/547#issuecomment-1307068033

I'll be closing this issue and sending out another update at https://github.com/umbraco/Umbraco.Cloud.Issues/issues/547 when the last detail regarding the email has been resolved.
