### ISSUE TITLE
Unable to login to authorize upgrade

### ISSUE THREAD

**Issue by callumbwhyte** [umbraco/Umbraco.Cloud.Issues#588]
### Issue description

When performing an upgrade from Umbraco v8.9 to v8.18 we encountered a major issue that prevented us from completing successfully.

After applying the upgraded DLLs, the site booted and took us to the "Authorize Upgrade" screen. However the Umbraco ID login option was gone, and so there was no way to login and proceed... Umbraco ID credentials do not work in the regular login fields.

This happened locally, on dev, and live.

<img width="1728" alt="Screenshot 2022-07-18 at 10 38 38" src="https://user-images.githubusercontent.com/16511093/179500684-c34e6cfa-9de8-447e-9aff-cf6145f8e0ac.png">

We worked around this in 2 different ways:

- Login to the CMS pre-upgrade, deploy the upgraded changes, and you are already authenticated from the previous session and so can proceed through the installer as normal
- Enable [unattended upgrades](https://our.umbraco.com/Documentation/Fundamentals/Setup/Upgrading/general-v8#run-an-unattended-upgrade) in config – _I would have thought this is the default for Cloud?_

Once the upgrade had completed the Umbraco ID login option returned.

**Comment by RyuLindow** [comment]
Hey @callumbwhyte 

We've had a couple of people reach out about this issue in the past and there are really only two solutions.

1. adding the UpgradeUnattended key
2. creating a local user before the upgrade and using its credentials to auth the upgrade but that's only an option for the local env

If you run the minor upgrade by clicking the upgrade button on Cloud then we add that setting as part of the upgrade but again, that's only when you do it via Cloud rather than local and then push to Cloud.

In this scenario, you need to add it yourself to web.config

On v9 and v10 it's added as an app setting to each environment on the infra level, so we got you covered on those versions.

Hope this clears it up!

**Comment by sajumb** [comment]
Hey @callumbwhyte ,
Sorry about the long wait, but here is a short update from our side.

The issue with missing upgrade buttons was resolved just after your latest post in this thread. It was due to some significant platform changes deactivated for a couple of weeks.

You are right that the _UpgradeUnattended_ setting preferable should be set to default for most cloud projects. We will look into this and come with an update when this has been considered. Thanks.

**Comment by callumbwhyte** [comment]
Thanks @sajumb,

Not wanting to muddy the waters, so if this is a separate issue please let me know...

I performed a v9.5 -> v10 upgrade on Friday and there were no buttons showing in the portal for this. I notice the docs make no reference to these buttons either? Are they only shown for minor upgrades, or is this feature completely dropped for V9+?

Following the upgrade docs was somewhat painful, having to manually delete files via Kudu, and when I came to deploy my changes the site did not restart / run the installer / etc until I manually intervened via Kudu. It would be great if this could be partly automated.

Cheers,
Callum

**Comment by sajumb** [comment]
It's perfectly fine to ask the question here. No muddy waters :-)

Umbraco Cloud currently offers autoupgrade for Umbraco Core when there is a new _patch_ for the minor that the cloud project uses.

While a manual update is offered for a cloud project when a new _minor_ is available. This is offered for all CMS versions and therefore also V9 and V10. You can find more details about autoupgrade and manual update here https://our.umbraco.com/documentation/Umbraco-Cloud/Upgrades/

As you have noted, Umbraco Cloud does not currently offer upgrades for _major_ versions. You therefore currently have to upgrade from V9.5 -> V10 manually as you have done (https://our.umbraco.com/documentation/Umbraco-Cloud/Upgrades/Upgrading-from-9-to-10/).

We are currently working an internal roadmap for the coming year that contains several exciting autoupgrade features. In addition to scheduled upgrades, we expect to look specifically at autoupgrades between major versions before long. So even though upgrades of major often go quite smoothly in Umbraco Cloud, it will become more automated and even simpler in the future.

Cheers

**Comment by callumbwhyte** [comment]
Thanks for clarifying @sajumb!

Can I then suggest a banner / indicator, similar for patches, when a major upgrade is available with a link to the docs for how to upgrade?

Cheers,
Callum
