### ISSUE TITLE
Can't create add another environment when secrets management contains value

### ISSUE THREAD

**Issue by PratheesUmbraco** [umbraco/Umbraco.Cloud.Issues#633]
### Issue description

When using the Secrets Management feature on Cloud, you will not be able to add a new environment. 

Following this [guide ](https://docs.umbraco.com/umbraco-cloud/set-up/private-nuget-feed#step-4-add-private-myget-feed-on-umbraco-cloud) you can add a private Nuget feed to your cloud project. That is all fine and dandy until you want to create a new environment. It will fail:
![image](https://user-images.githubusercontent.com/74538774/218435616-db43339e-0a68-4afe-8aa3-5f149dbfa18b.png)

Secrets management is per environment and therefore it fails in creating a new environment. It should be project-based instead.
And maybe the environment specific as well as the option for different secrets for Live should be available. 

Steps to reproduce:

1. Create a new project or use an existing one with only one environment

2. Clone it down

3. Follow the [guide](https://docs.umbraco.com/umbraco-cloud/set-up/private-nuget-feed#step-4-add-private-myget-feed-on-umbraco-cloud) and add a package to MyGetFeed. Remember to add the NuGet.Config

4. Make sure it runs locally

5. Add the values for the Secrets Management in the Portal

6. Push the added package from local to Cloud

7. Create a Dev environment

**Comment by sajumb** [comment]
Thanks for the bug report. We have added it to our backlog and expect to handle it within the next weeks.

**Comment by sajumb** [comment]
We have launched the concept "Shared secrets" which you will find on the secrets management page.

**_Shared Secrets_** are utilized across all environments and will be seamlessly integrated into any new environment you create. Shared Secrets are particularly well-suited for safeguarding credentials necessary for project development, such as access to private NuGet feeds.
Utilizing environment-specific secrets for private NuGet feeds will result in the unsuccessful creation of new environments due to the unknown status of the secret. In such instances, Shared Secrets should be used.
