### ISSUE TITLE
Feature: automatic synchronization on document types created in Live to Dev

### ISSUE THREAD

**Issue by romeguarin** [umbraco/Umbraco.Cloud.Issues#668]
### Issue description

As the title suggests it would be good to have an option or service when a Document type is created in Live, it should also create or sync the document to Development upon Save.

**Comment by PascalIcatt** [comment]
It might break the current dev, and while developing I am reluctant to my environment changing magically, but it would be nice to have this as an option, or maybe a ""Live changes bucket" that shows new/incoming differences?

**Comment by c9mb** [comment]
@romeguarin Can't you do this with uSync ?

**Comment by romeguarin** [comment]
> @romeguarin Can't you do this with uSync ?

Is this possible in heartcore?

**Comment by RyuLindow** [comment]
Hi @romeguarin It's not, as Heartcore is a SaaS product.

Also, please note that the recommended workflow on UC is dev>stage>live and we don't support restoring schemas in the opposite direction nor do we plan to.

What you can do is to delete your dev env and then recreate it which takes a copy of the live env. This'll result in what you've asked for.

**Comment by romeguarin** [comment]
> Hi @romeguarin It's not, as Heartcore is a SaaS product.
> 
> Also, please note that the recommended workflow on UC is dev>stage>live and we don't support restoring schemas in the opposite direction nor do we plan to.
> 
> What you can do is to delete your dev env and then recreate it which takes a copy of the live env. This'll result in what you've asked for.

Yup, that's the last option. However some users still tend to create in Live first. If the recommended is "dev > live" there should be at least a guard or validation for it. It's not ideal for the development to be recreated every time.

**Comment by RyuLindow** [comment]
I agree that it's not ideal for you to recreate dev, nor should you do that.

My recommendation would be to either teach the recommended workflow to anybody with access to the setting section who can update the schemas or to access that section for people who should and leave it only for the selected few you know won't work on live.

It's never recommended to do dev work in production and that's why we have the dev + stage environments on Cloud :)

**Comment by romeguarin** [comment]
@RyuLindow we had to recreate the Dev and Stage environments but it has bought up a lot of issues. some of the contents are no longer returned by Umbraco API (via Filter endpoint). And noticed that I lost access to the GraphQL, WebHooks and Preview features on Dev and Staging environments. Why would you recommend recreating when it causes issues?

**Comment by RyuLindow** [comment]
@romeguarin something must have gone wrong in the env creation/deletion process. There's no reason for me not to recommend you the best solution I can provide you with and I'm not sure why you would think otherwise :)

If you still haven't, please reach out to the support team.

They'll check why this is happening and help resolve your issues.

**Comment by romeguarin** [comment]
@RyuLindow recreating the Dev is not a workaround if **something** could go wrong in the creation / deletion process. Suggest a workaround that does not create further issues and headaches. 
Aside from losing some features, some contents that was restored to Dev / Staging from Live are no longer returned by Umbraco API when using the Filter endpoint.

I've reached out to support since Monday and we're about to go Production with the contents soon.
