### ISSUE TITLE
How to check expiry date and change SAS key for Umbraco Blob Storage Connection

### ISSUE THREAD

**Issue by IamAnthonyKwan** [umbraco/Umbraco.Cloud.Issues#670]
### Issue description

We want to change the Shared access signature URL (SAS) keys for Umbraco Blob Storage Connection due to some security reasons. However, this action can only done by Umbraco support. Please advise how to check the expiry date of current active SAS key(s) and is it possible to change the SAS key on DEV/Staging/Live environment?

**Comment by sajumb** [comment]
Hi @IamAnthonyKwan,
For security-related inquiries and tasks like changing the Shared Access Signature (SAS) keys for Umbraco Blob Storage Connection, it's best to communicate directly with Umbraco support rather than posting on public issue trackers. To get assistance with your specific situation, follow these steps:

**1. Use the Chat Option**: Log in to your Umbraco Cloud account and look for a chat option or a support portal within the platform. This will likely be the most direct and efficient way to communicate with Umbraco's support team.

**2. Expiry Date of Current SAS Key(s)**: When you reach out to Umbraco support, ask them to check the expiry date of your current active SAS key(s). They will be able to provide you with the necessary information.

**3. Changing SAS Key on Environments**: Inquire with Umbraco support whether it is possible to change the SAS key on DEV, Staging, and Live environments. They will guide you through the process and let you know if it's feasible and, if so, how to proceed safely.

Remember, Umbraco support is well-equipped to handle security-related matters and provide you with the most accurate and up-to-date information. By using the chat option, you can have a private conversation with the support team, ensuring the security of your sensitive information while receiving the necessary assistance.
