### ISSUE TITLE
Kudu deployment issue due to too long filenames

### ISSUE THREAD

**Issue by jemayn** [umbraco/Umbraco.Cloud.Issues#687]
### Issue description

After a recent refactor I tried pushing my code and received an error in the console:
![image](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/79840720/eaea1c98-9c99-4874-a93c-9749e6b7d8da)

When I dug deeper in Kudu I found this error message in the deployment log:

```
unable to create file ******/Presentation/Website/Core/Migrations/GeneratedMigrations/ProductInFavouriteListMigration/20230907091209_ProductInFavouriteListInitialCreate.Designer.cs: Filename too long\nAlready on 'master'\n\r\nC:\Program Files\Git\cmd\git.exe checkout master --force,,2
```

Parts of the filenames are auto generated in EF Core and do take up quite a bit of space - however the full path from root of the repo was 159 chars (with the project name that I removed in the example above).

Which is a lot shorter than the 260 limit in Windows.

No clear error was shown both in the portal and in my local git window when pushing - the error I found was from the newest deployment based on the timestamp, but the "active" deployment in the deployment folder was stuck on a previous one until I shortened the filename.

I reached out to Cloud support but they couldn't answer what the max allowed file length is.

My issue/request here is twofold:
1. Would be great to know what the max allowed file length is generally - that way we can write a script to check before we deploy. (159 was too long, renaming some things to 140 chars made it work again)
2. Would be awesome to get the proper error message in the Cloud portal so I don't have to go digging in Kudu 🙂

**Comment by sajumb** [comment]
Hi @jemayn,
Thank you for bringing this issue to our attention. I understand the inconvenience you've faced due to the lack of a clear error message and the uncertainty around the maximum allowed file length. Let's address your concerns one by one.

While Windows does have a 260-character limit for file paths, other factors could contribute to this issue, such as underlying file system constraints or specific limitations within the deployment process. I will talk with the team and provide a definitive answer. In the meantime, writing a script to check the file length before deployment, as you suggested, could be a good precautionary measure.

I agree that having a clear and informative error message in the Cloud portal would save time and effort. We'll look into improving the error messaging to make it more user-friendly and informative. We call this initiative "Enhanced Process Visibility for Umbraco Cloud" and here we also have the ambition to highlight potential issues and even resolve them wherever possible. This should help our users avoid having to dig into Kudu logs for troubleshooting which sometimes still is the case.

**Comment by sajumb** [comment]
I made a couple of searches and found the following examples. The conclusion is, however, that I cannot give you an exact number of chars as it depends on paths that often will change from project to project.

The most likely root cause for the "Filename too long" error in the context of an Azure service is the inherent file path length limitation of the underlying Windows-based system, which is generally 260 characters. This limit includes the drive letter, folders, subfolders, file name, and file extension.

The path
Presentation/Website/Core/Migrations/GeneratedMigrations/ProductInFavouriteListMigration/20230907091209_ProductInFavouriteListInitialCreate.Designer.cs

has 144 characters.

Now, consider that this path will be prefixed by the root directory where your project resides. For example, if your project is in a folder like C:\Projects\MyApp\, that would add another 17 characters, making it 161 characters long.

If you're deploying this through Azure App Service, there might be an additional system-defined directory structure, which could look something like D:\home\site\wwwroot\. This would add another 20 characters, totaling 181 characters.

Git internal folders: Git uses a .git directory for its internal files, which could add to the path length.
Temporary build or deployment folders: Azure DevOps or other CI/CD tools might use temporary directories that add to the path length.

Even without considering potential additional lengths from Git or CI/CD processes, the path is already 181 characters long. Depending on the Azure service and how it manages file paths, you could easily approach or exceed the 260-character limit of a Windows-based system.

Given these calculations, it's quite plausible that you're hitting the file path length limitation, especially if additional system or tool-specific directories are being appended to the file path during deployment or runtime.
