### ISSUE TITLE
V7 - Sites were not auto-updated by UC and are now EOL

### ISSUE THREAD

**Issue by c9mb** [umbraco/Umbraco.Cloud.Issues#688]
### Issue description

I have a number of v7 sites that clients wish to remain on for the time being.

They understand the issues and limitations, but also know their business needs and budgets.

However, the sites are all stuck on 7.15.7 because auto-updates for v7 have not been run by UC for the last few updates.

This non-updating of v7 sites started when problems were encountered in the 7.15.8 updates - not just my sites, but a general problem - and Umbraco abandoned the updating of v7 sites.

When I made enquiries about this with support, I was told that there is a problem in the updater, and that it would be fixed - "at some time in the future".

However, the "fix" was apparently to simply ignore auto-updates and v7 sites were allowed to drift further and further behind the current release version - now 7.15.11

Given that some of these releases were security patches and v7 was still in 'security phase' at the time, I would have thought it reasonable to expect the sites be updated with those patches.

Each time I asked when the auto-updates would be fixed, I was given the same answer, or told to try and figure it out myself.

Of course, now that v7 is EOL there is no intention to auto-update them to the last release, and the problem becomes mine.

I note there is a thread on the Umbraco-CMS indicating that upgrading from 7.15.10 to 7.15.11 fails - https://github.com/umbraco/Umbraco-CMS/issues/14873 - so clearly this is not going to be straight forward.

So, how to deal with getting these 7.15.7 sites upgraded to 7.15.11 ?

**Comment by sajumb** [comment]
Hi @c9mb 

Thank you for bringing up your concerns regarding the auto-updates for v7 sites. We understand the importance of keeping your sites up-to-date, especially when it comes to security patches.

I'm pleased to inform you that we are actually just about to auto-upgrade to the latest patch for v7 sites, V 7.15.11, starting on Tuesday, 2nd October.  We have addressed the issues that led to the suspension of auto-updates and are confident that the upcoming upgrade will be executed smoothly. The update will be monitored closely and can take the whole week before all relevant cloud projects have been updated with this patch. We intend to upgrade V7 cloud projects with all patch versions later than V 7.17.5 (as this version contains a breaking change).

This will be the last patch auto-upgraded for V7 cloud projects as it has reached its End-of-Life (EOL) status. 

Regarding the thread on Umbraco-CMS about upgrading from 7.15.10 to 7.15.11, we have seen this issue in our initial tests but will monitor the projects closely in order to ensure that the auto-upgrade process will not encounter the same problems.

For more information and real-time updates, you can visit the status page of Umbraco Cloud at [status.umbraco.io](https://status.umbraco.io/) or refer to the specific scheduled update message at [https://status.umbraco.io/incidents/5r5m1k7k54b2](https://status.umbraco.io/incidents/5r5m1k7k54b2).

If you have any specific concerns or questions about this upcoming auto-upgrade, please feel free to reach out to our support team. We are committed to making this transition as seamless as possible for you and all our users.

Thank you for your patience and understanding.

**Comment by sajumb** [comment]
We have now successfully completed the upgrade to the patch V.7.17.11 for all candidates.
Let me know if you have any further questions.
