### ISSUE TITLE
Starter Kit Package bug

### ISSUE THREAD

**Issue by PetrSou** [umbraco/Umbraco.Cloud.Issues#705]
### Issue description

we are creating Starter Kit Package, but we face the following issue:
- we follow all the steps, we create the package in the backoffice, then use the package.zip in another project to generate the nuget package
- then when we use that nuget package in another empty project, all content pages, document types and templates are imported, BUT incorrectly assigned. The Content pages dont have assigned the template as on the original project, it seems that they have assigned THE DEFAULT template for its document type

Steps to reproduce - create package for content page, where its document type has multiple assigned templates and the content page uses the NON DEFAULT template

Version used 12.1.1

 The templates are getting packaged properly and also are imported, just not properly assigned.

We inspected the package.xml and it seems to be a problem with the way how the template is referenced. It looks like there is only reference to the documentType , NOT the template

**Comment by sajumb** [comment]
Hi @PetrSou 
Thank you for bringing this matter to our attention. Based on your description, it appears that this issue may be more relevant to the Umbraco CMS rather than the Umbraco Cloud. Could you please confirm this? If it is indeed related to the Umbraco CMS, we kindly request that you open an issue at [Umbraco CMS Issues](https://github.com/umbraco/Umbraco-CMS/issues) and close the current thread. However, if this issue pertains to Umbraco Cloud, we would appreciate additional details to understand it better.

**Comment by PetrSou** [comment]
moved to Umbraco CMS
