### ISSUE TITLE
SVG media has no cache

### ISSUE THREAD

**Issue by Epenance** [umbraco/Umbraco.Cloud.Issues#73]
Usual media items has a `Cache-Control: public, must-revalidate, max-age=604800` but SVG media items has `Cache-Control: no-cache` I suppose this is an oversight.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Steps to reproduce

Simply upload an SVG to the media library, then try to request it in the browser and see that it has the `Cache-Control: no-cache` instead of the max-age that other media items have.

### Expected result

Normal media items have: `Cache-Control: public, must-revalidate, max-age=604800`

### Actual result

SVG Media items have: `Cache-Control: no-cache`

**Comment by ronaldbarendse** [comment]
This is probably because ImageProcessor sets those `Cache-Control` headers... So this is just a configuration issue, as you're depending on the default server (IIS) configuration to send the wanted header.

Also, make sure you have included the SVG extension MIME-mapping in your `Web.config`:
```xml
<system.webServer>
	<staticContent>
		<remove fileExtension=".svg" />
		<mimeMap fileExtension=".svg" mimeType="image/svg+xml" />
	</staticContent>
</system.webServer>
```

Setting the correct expiry might also need some logic, as ImageProcessor only sets a high max-age if it can find a cache buster in the query string (`v` or `rnd`).

**Comment by nul800sebastiaan** [comment]
Doesn't need to be ImageProcessor - if the SVG doesn't have a querystring ImageProcessor should leave it alone. There's not a lot IP can do with SVGs anyway, so it might just be a problem that it does NOT run through IP. Umbraco doesn't set cache headers anywhere, so this is using whatever the default in IIS uses.

In any case, I don't see the problem on my end, are you sure you're looking at the response headers instead of the request headers? We don't actively send "no-cache".

![image](https://user-images.githubusercontent.com/304656/56879045-44c57100-6a57-11e9-978d-8284ccf428e6.png)

From what I'm reading the browser has seen this image before, if the server sends a header Modified-Since that doesn't match the If-Modified-Since date in the request headers, it needs to refresh the image. So it seems just fine, browser cache works as expected. I'll close this for now, let me know if I missed something.

**Comment by Epenance** [comment]
In your own example Max-age is 0 as well meaning your browser wont cache it. It is also still present on our own cloud solution: 
![image](https://user-images.githubusercontent.com/6709028/56880742-40e91d00-6a5e-11e9-9466-fdcbcdde29cb.png)

I'd expect SVG's to act the same way as any other image
