### ISSUE TITLE
Misleading and inaccurate error in Umbraco Cloud CICD deploy process

### ISSUE THREAD

**Issue by eqtr-ab** [umbraco/Umbraco.Cloud.Issues#778]
### Issue description

Umbraco Cloud's CICD deploy process will return a "version downgrade" error if it detects a csproj file in the supplied ZIP file with a lower version, even if that csproj file is not referenced in the solution. This is fair enough, but the error message it generates is completely inaccurate and does not reflect the project file containing the outdated reference. 

For a deployment with this error message:

```
info: Received HTTP response headers after 98.3815ms - 200
info: End processing HTTP request after 100.0793ms - 200
info: Executed step: Download update
info: Executing step: Extract Update
info: Extracting zip /app/work/Update.zip to /app/work/Update
info: Executed step: Extract Update
info: Executing step: Checking versions
fail: Update failed with message: Cannot apply update because the following packages would be downgraded: Package: Umbraco.Cms, Version: 13.4.0, Project file: /repository/VistaHealth.Core/VistaHealth.Core.csproj. Package: Umbraco.Cms, Version: 13.4.0, Project file: /repository/src/VistaHealth/VistaHealth.csproj. Package: Umbraco.Cms, Version: 13.4.0, Project file: /repository/VistaHealth.Core/VistaHealth.Core.csproj. Package: Umbraco.Cms, Version: 13.4.0, Project file: /repository/src/VistaHealth/VistaHealth.csproj.
fail: Error executing step: Umbraco.Cloud.Deployment.UpdateExecutor.Umbraco.Steps.CheckVersions Cannot apply update because the following packages would be downgraded: Package: Umbraco.Cms, Version: 13.4.0, Project file: /repository/VistaHealth.Core/VistaHealth.Core.csproj. Package: Umbraco.Cms, Version: 13.4.0, Project file: /repository/src/VistaHealth/VistaHealth.csproj. Package: Umbraco.Cms, Version: 13.4.0, Project file: /repository/VistaHealth.Core/VistaHealth.Core.csproj. Package: Umbraco.Cms, Version: 13.4.0, Project file: /repository/src/VistaHealth/VistaHealth.csproj.
info: Publishing update failed event
info: Executing step: Delete updating marker
info: Start processing HTTP request DELETE https://[snip].umbraco.io/api/vfs/site/locks/updating
info: Sending HTTP request DELETE https://[snip].umbraco.io/api/vfs/site/locks/updating
info: Received HTTP response headers after 146.6575ms - 200
info: End processing HTTP request after 148.7358ms - 200
info: Executed step: Delete updating marker
```

The project files at the specified paths had the correct version (13.4.0), but there were project files not referenced by the solution (13.3.2) at the paths `/src/VistaHealth.Umbraco.Core/VistaHealth.Umbraco.Core.csproj` and `/src/VistaHealth.Umbraco/VistaHealth.Umbraco.csproj`, neither of which are referred to in the error message returned from the CICD status endpoint. 

I have liaised directly with Umbraco support on this issue over a prolonged period, but this issue remains unsolved. The deployment process should either a) ignore projects which are not referenced in the solution and therefore not part of the build process, or b) report an accurate error message so that the correct packages can be identified and either updated or eliminated.

**Comment by Aaen** [comment]
Hi @eqtr-ab 

I have talked with my colleague about this issue 

The message you are seeing here is coming from the API:
You have started a deployment and are "pinging" an endpoint to get updates about the deployment.
The endpoint is returning this error because the package they uploaded contains a reference to "Umbraco.Cms" which is lower than 13.4

This is expected behavior of the system - We want to prevent people from accidentally downgrading packages which cloud depends upon.

We have this troubleshooting article to help people deal with this.
[https://docs.umbraco.com/umbraco-cloud/set-up/project-settings/umbraco-cicd/troubleshooting#cannot-apply-update-becaus[…]ackage-umbraco.-abc-version](https://docs.umbraco.com/umbraco-cloud/set-up/project-settings/umbraco-cicd/troubleshooting#cannot-apply-update-because-the-following-packages-would-be-downgraded-package-umbraco.-abc-version)

As the article explains: We check ALL csproj files part of the uploaded package.
So if one old csproj file contains an old package reference - your deployment will fail in a similar way.

Can you please clearly what you mean by option b
>  b) Report an accurate error message so that the correct packages can be identified and either updated or eliminated.

**Comment by eqtr-ab** [comment]
By option b, I mean that the names and paths of the projects containing the outdated reference should be accurate and reflect the project which needs to be updated, instead of pointing to a project which has already been updated. As outlined in my original post, the message does not correctly indicate which project file contains the downgraded reference - the project files referenced in the error message were already upgraded to 13.4.0.

**Comment by eqtr-ab** [comment]
For clarity, @Aaen - here is the screenshot that you sent me through the Umbraco support portal demonstrating what I am talking about in my previous comment. Compare the names of the projects with the 13.3.2 references to those highlighted in the error message I pasted into my original post.
![Skærmbillede 2024-07-09 kl  11 00 21](https://github.com/umbraco/Umbraco.Cloud.Issues/assets/48097016/e9fb5f02-eb62-4069-9dbf-e530a420e4de)

**Comment by mclausen** [comment]
Hi @eqtr-ab ,
From what I can see from the first error message described it does not indicate the problematic dependencies, and that is something we can improve. 

On an additional question how come these versions are not aligned to the latest?

**Comment by eqtr-ab** [comment]
Thank you @mclausen. These orphaned projects were left over from a previous project structure, weren't referenced by the Visual Studio solution, and therefore weren't included in our recent upgrade which was done through the NuGet management tool in Visual Studio. We have now removed these projects from our source control as they did not contain any source code.

It's worth mentioning that we had the same problem when we were still opted-in to automatic minor upgrades on Umbraco cloud, i.e. the automated upgrade procedure updated all the csproj files referenced by the solution but didn't update those which weren't referenced by the solution. This resulted in a broken deployment with the same circumstances outlined in the original ticket, which both ourselves and Umbraco support struggled to diagnose thanks to the inaccurate error being discussed.

**Comment by mclausen** [comment]
Thank you for elaborating @eqtr-ab, that makes good sense. I've added the issue to our internal tracker we'll do a deep dive into the issue.

I will return with an update as soon as we have one.

**Comment by jesp209i** [comment]
hi @eqtr-ab
Thanks for the feedback about a misleading error message.
We have updated the flow to generate a more informative error to help troubleshoot issues related to the downgrade error.

This is a sample of what the new error looks like:
`Cannot apply update because the following packages would be downgraded: Package: Umbraco.Cms, Version: 13.4.0 ==> Project file: /Update/src/MyAwesomeProject.Code/MyAwesomeProject.Code.csproj contains lower Version: 13.1.0 .`

The change is out as I type  🚀 
Again thanks for your feedback
