### ISSUE TITLE
"Deploy to [environment]" logic resolves merge conflicts automatically - why?

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco.Cloud.Issues#779]
### Issue description

I'm currently figuring out some of the caveats for deployment on Umbraco Cloud, as part of an overhaul on our CI/CD processes.

I have a `dev` and `live` environment which I purposely gave a merge conflict by adjusting the same file. The flow whenever you press the "Deploy to [environment]" button is something like:
1. Clone live
2. Pull dev-master
3. Merge dev-master into live-master
4. Commit the result
5. Push to both

However, whenever a merge conflict occurs. It seems to always let the lower environment win (in this case dev).

Obviously, releasing to Cloud is a matter of protocol. You make sure to pull in changes from live into dev, before you try to deploy, and other such unwritten rules. 

However, we all make mistakes, so I'm curious what the reasoning is behind trying to automatically resolve conflicts (and in particular by always deciding "dev wins").

Just imagine you have a Umbraco Forms UDA-file. On dev you changed it, and on live the client changed. You forget the step to sync changes back to dev. You deploy, dev overwrites the live and immediately runs a deploy import. All seems fine, a week later the client notices his form is messed up and now you have two different versions of data on your hands.

I much rather get a big fat error that have to resolve manually, than to have to have things silently (and wrongfully) fixed for me. Umbraco Forms UDA is only one example.

So what is the reason behind doing this? Why let dev win and not live? And most importantly: can we disable this behavior?

I'm currently at the point of either replicating the "Deploy to [environment]" logic to my own CI/CD, or skipping it all together and just always directly push to the different environments, so I'm in control on what happens.

**Comment by mikkelhm** [comment]
Hi @LennardF1989 

Thanks for asking - The idea behind the workflow is that schema and file changes - that would be the uda files are made and maintained by developers of the site, so those would always flow from left to right (dev-stage-live), while content could run the other direction, so you'd be able to restore content on stage and dev, once it has been created. The flow that is intended on Umbraco Cloud is that anything in the backoffice on any cloud environment that can change a file, is closed off and only developers of the site are allowed to make changes - those changes comes in via git, when changing the repositories locally or in development environments. 
We will throw a big fat error, if we are unable to apply the merging strategy though, and at that point it is up to the developers of the site to manually handle the conflict.

I'm a bit unsure about the forms uda file problem. Forms should be stored in the database and not in uda files anymore - we addressed that problem in earlier version of Umbraco, due to exactly the issue your are describing. Forms are treated as content and are transferred between environments just like any other content (and media) -> https://docs.umbraco.com/umbraco-cloud/deployments/umbraco-forms-on-cloud.

It is not possible to disable the feature, but you are welcome to go start a discussion as a feature request on this repository. Then we can get a process going on weather it is something that should be implemented in the future
