### ISSUE TITLE
"Environment busy"-error shows up as extraction error

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco.Cloud.Issues#78]
If an environment ends up with a "busy" error it shows up as an extraction error. The error also stays until you manually remove the error marker. The error should disappear when the environment is ready again.

<img width="625" alt="Screenshot 2019-04-12 at 11 48 47" src="https://user-images.githubusercontent.com/6078361/56028932-91037800-5d19-11e9-8c2b-aa6b4b75de5b.png">

**Comment by nul800sebastiaan** [comment]
Hi @madsrasmussen - just going through some old issues here. I have talked to the team and after multiple rounds of investigation it seems that we can't "just" remove the marker since we can't actually know when we're "done" and have no more errors. The guidance for this has changed since you created the issue and we no longer recommend manually removing files, AFAIK all problems should be fixed by making updates locally and pushing to Cloud, which will then trigger a new attempt to extract everything. 

This process is obviously not ideal yet and we have a few other issues covering that (mostly related to: every attempt at fixing might trigger another conflict, we should bundle up everything and present that back to the user to fix so they don't get stuck in having to do multiple attempts).

As such, I'll close this issue for now while we concentrate on making fixing conflicts better.
